//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{FishbowlSDK}DB_ID" minOccurs="0"/>
 *         &lt;element name="Name" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Attn" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Street" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="City" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Zip" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="LocationGroupId" type="{FishbowlSDK}DB_ID" minOccurs="0"/>
 *         &lt;element name="Default" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="Residential" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="Type" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}State"/>
 *         &lt;element ref="{FishbowlSDK}Country"/>
 *         &lt;element ref="{FishbowlSDK}AddressInformationList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "name",
    "attn",
    "street",
    "city",
    "zip",
    "locationGroupId",
    "_default",
    "residential",
    "type",
    "state",
    "country",
    "addressInformationList"
})
@XmlRootElement(name = "Address")
public class Address {

    @XmlElement(name = "ID")
    protected BigInteger id;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Attn")
    protected String attn;
    @XmlElement(name = "Street", required = true)
    protected String street;
    @XmlElement(name = "City")
    protected String city;
    @XmlElement(name = "Zip")
    protected String zip;
    @XmlElement(name = "LocationGroupId")
    protected BigInteger locationGroupId;
    @XmlElement(name = "Default")
    protected Boolean _default;
    @XmlElement(name = "Residential")
    protected Boolean residential;
    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "State", required = true)
    protected State state;
    @XmlElement(name = "Country", required = true)
    protected Country country;
    @XmlElement(name = "AddressInformationList")
    protected AddressInformationList addressInformationList;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the attn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttn() {
        return attn;
    }

    /**
     * Sets the value of the attn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttn(String value) {
        this.attn = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZip() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZip(String value) {
        this.zip = value;
    }

    /**
     * Gets the value of the locationGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocationGroupId() {
        return locationGroupId;
    }

    /**
     * Sets the value of the locationGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocationGroupId(BigInteger value) {
        this.locationGroupId = value;
    }

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefault(Boolean value) {
        this._default = value;
    }

    /**
     * Gets the value of the residential property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isResidential() {
        return residential;
    }

    /**
     * Sets the value of the residential property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setResidential(Boolean value) {
        this.residential = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link State }
     *     
     */
    public State getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link State }
     *     
     */
    public void setState(State value) {
        this.state = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setCountry(Country value) {
        this.country = value;
    }

    /**
     * Gets the value of the addressInformationList property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInformationList }
     *     
     */
    public AddressInformationList getAddressInformationList() {
        return addressInformationList;
    }

    /**
     * Sets the value of the addressInformationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInformationList }
     *     
     */
    public void setAddressInformationList(AddressInformationList value) {
        this.addressInformationList = value;
    }

}
