//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CartonNum" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="TrackingNum" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="FreightWeight" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="FreightAmount" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}ShippingItems" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cartonNum",
    "trackingNum",
    "freightWeight",
    "freightAmount",
    "shippingItems"
})
@XmlRootElement(name = "Carton")
public class Carton {

    @XmlElement(name = "CartonNum")
    protected String cartonNum;
    @XmlElement(name = "TrackingNum")
    protected String trackingNum;
    @XmlElement(name = "FreightWeight")
    protected String freightWeight;
    @XmlElement(name = "FreightAmount")
    protected String freightAmount;
    @XmlElement(name = "ShippingItems")
    protected ShippingItems shippingItems;

    /**
     * Gets the value of the cartonNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCartonNum() {
        return cartonNum;
    }

    /**
     * Sets the value of the cartonNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCartonNum(String value) {
        this.cartonNum = value;
    }

    /**
     * Gets the value of the trackingNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingNum() {
        return trackingNum;
    }

    /**
     * Sets the value of the trackingNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingNum(String value) {
        this.trackingNum = value;
    }

    /**
     * Gets the value of the freightWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreightWeight() {
        return freightWeight;
    }

    /**
     * Sets the value of the freightWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreightWeight(String value) {
        this.freightWeight = value;
    }

    /**
     * Gets the value of the freightAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreightAmount() {
        return freightAmount;
    }

    /**
     * Sets the value of the freightAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreightAmount(String value) {
        this.freightAmount = value;
    }

    /**
     * Gets the value of the shippingItems property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingItems }
     *     
     */
    public ShippingItems getShippingItems() {
        return shippingItems;
    }

    /**
     * Sets the value of the shippingItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingItems }
     *     
     */
    public void setShippingItems(ShippingItems value) {
        this.shippingItems = value;
    }

}
