//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{FishbowlSDK}CustomerID" minOccurs="0"/>
 *         &lt;element name="AccountID" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}Status" minOccurs="0"/>
 *         &lt;element name="DefPaymentTerms" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="DefShipTerms" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="TaxRate" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Name" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Number" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="DateCreated" type="{FishbowlSDK}DATETIMETYPE" minOccurs="0"/>
 *         &lt;element name="DateLastModified" type="{FishbowlSDK}DATETIMETYPE" minOccurs="0"/>
 *         &lt;element name="LastChangedUser" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="CreditLimit" type="{FishbowlSDK}PRICETYPE" minOccurs="0"/>
 *         &lt;element name="TaxExempt" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="TaxExemptNumber" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Note" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="ActiveFlag" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="AccountingID" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="DefaultSalesman" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="DefaultCarrier" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="JobDepth" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="ParentID" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="PipelineAccount" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="URL" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}Addresses" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}CustomFields" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerID",
    "accountID",
    "status",
    "defPaymentTerms",
    "defShipTerms",
    "taxRate",
    "name",
    "number",
    "dateCreated",
    "dateLastModified",
    "lastChangedUser",
    "creditLimit",
    "taxExempt",
    "taxExemptNumber",
    "note",
    "activeFlag",
    "accountingID",
    "defaultSalesman",
    "defaultCarrier",
    "jobDepth",
    "parentID",
    "pipelineAccount",
    "url",
    "addresses",
    "customFields"
})
@XmlRootElement(name = "Customer")
public class Customer {

    @XmlElement(name = "CustomerID")
    protected BigInteger customerID;
    @XmlElement(name = "AccountID")
    protected BigInteger accountID;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "DefPaymentTerms")
    protected String defPaymentTerms;
    @XmlElement(name = "DefShipTerms")
    protected String defShipTerms;
    @XmlElement(name = "TaxRate")
    protected String taxRate;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Number")
    protected String number;
    @XmlElement(name = "DateCreated")
    protected String dateCreated;
    @XmlElement(name = "DateLastModified")
    protected String dateLastModified;
    @XmlElement(name = "LastChangedUser")
    protected String lastChangedUser;
    @XmlElement(name = "CreditLimit")
    protected String creditLimit;
    @XmlElement(name = "TaxExempt")
    protected Boolean taxExempt;
    @XmlElement(name = "TaxExemptNumber")
    protected String taxExemptNumber;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "ActiveFlag")
    protected Boolean activeFlag;
    @XmlElement(name = "AccountingID")
    protected String accountingID;
    @XmlElement(name = "DefaultSalesman", required = true)
    protected String defaultSalesman;
    @XmlElement(name = "DefaultCarrier", required = true)
    protected String defaultCarrier;
    @XmlElement(name = "JobDepth")
    protected BigInteger jobDepth;
    @XmlElement(name = "ParentID")
    protected BigInteger parentID;
    @XmlElement(name = "PipelineAccount")
    protected BigInteger pipelineAccount;
    @XmlElement(name = "URL")
    protected String url;
    @XmlElement(name = "Addresses")
    protected Addresses addresses;
    @XmlElement(name = "CustomFields")
    protected CustomFields customFields;

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomerID(BigInteger value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the accountID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountID() {
        return accountID;
    }

    /**
     * Sets the value of the accountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountID(BigInteger value) {
        this.accountID = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the defPaymentTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefPaymentTerms() {
        return defPaymentTerms;
    }

    /**
     * Sets the value of the defPaymentTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefPaymentTerms(String value) {
        this.defPaymentTerms = value;
    }

    /**
     * Gets the value of the defShipTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefShipTerms() {
        return defShipTerms;
    }

    /**
     * Sets the value of the defShipTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefShipTerms(String value) {
        this.defShipTerms = value;
    }

    /**
     * Gets the value of the taxRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxRate() {
        return taxRate;
    }

    /**
     * Sets the value of the taxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxRate(String value) {
        this.taxRate = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateCreated(String value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the dateLastModified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateLastModified() {
        return dateLastModified;
    }

    /**
     * Sets the value of the dateLastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateLastModified(String value) {
        this.dateLastModified = value;
    }

    /**
     * Gets the value of the lastChangedUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastChangedUser() {
        return lastChangedUser;
    }

    /**
     * Sets the value of the lastChangedUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastChangedUser(String value) {
        this.lastChangedUser = value;
    }

    /**
     * Gets the value of the creditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditLimit() {
        return creditLimit;
    }

    /**
     * Sets the value of the creditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditLimit(String value) {
        this.creditLimit = value;
    }

    /**
     * Gets the value of the taxExempt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTaxExempt() {
        return taxExempt;
    }

    /**
     * Sets the value of the taxExempt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTaxExempt(Boolean value) {
        this.taxExempt = value;
    }

    /**
     * Gets the value of the taxExemptNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptNumber() {
        return taxExemptNumber;
    }

    /**
     * Sets the value of the taxExemptNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptNumber(String value) {
        this.taxExemptNumber = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the activeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActiveFlag() {
        return activeFlag;
    }

    /**
     * Sets the value of the activeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActiveFlag(Boolean value) {
        this.activeFlag = value;
    }

    /**
     * Gets the value of the accountingID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingID() {
        return accountingID;
    }

    /**
     * Sets the value of the accountingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingID(String value) {
        this.accountingID = value;
    }

    /**
     * Gets the value of the defaultSalesman property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultSalesman() {
        return defaultSalesman;
    }

    /**
     * Sets the value of the defaultSalesman property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultSalesman(String value) {
        this.defaultSalesman = value;
    }

    /**
     * Gets the value of the defaultCarrier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultCarrier() {
        return defaultCarrier;
    }

    /**
     * Sets the value of the defaultCarrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultCarrier(String value) {
        this.defaultCarrier = value;
    }

    /**
     * Gets the value of the jobDepth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getJobDepth() {
        return jobDepth;
    }

    /**
     * Sets the value of the jobDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setJobDepth(BigInteger value) {
        this.jobDepth = value;
    }

    /**
     * Gets the value of the parentID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParentID() {
        return parentID;
    }

    /**
     * Sets the value of the parentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParentID(BigInteger value) {
        this.parentID = value;
    }

    /**
     * Gets the value of the pipelineAccount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPipelineAccount() {
        return pipelineAccount;
    }

    /**
     * Sets the value of the pipelineAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPipelineAccount(BigInteger value) {
        this.pipelineAccount = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link Addresses }
     *     
     */
    public Addresses getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addresses }
     *     
     */
    public void setAddresses(Addresses value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the customFields property.
     * 
     * @return
     *     possible object is
     *     {@link CustomFields }
     *     
     */
    public CustomFields getCustomFields() {
        return customFields;
    }

    /**
     * Sets the value of the customFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomFields }
     *     
     */
    public void setCustomFields(CustomFields value) {
        this.customFields = value;
    }

}
