//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="TagQueryRs" type="{FishbowlSDK}TagQueryRsType"/>
 *         &lt;element name="PartTagQueryRs" type="{FishbowlSDK}PartTagQueryRsType"/>
 *         &lt;element name="LocationQueryRs" type="{FishbowlSDK}LocationQueryRsType"/>
 *         &lt;element name="TagMoveRs" type="{FishbowlSDK}TagMoveRsType"/>
 *         &lt;element name="CustomerListRs" type="{FishbowlSDK}CustomerListRsType"/>
 *         &lt;element name="CustomerNameListRs" type="{FishbowlSDK}CustomerNameListRsType"/>
 *         &lt;element name="CustomerSaveRs" type="{FishbowlSDK}CustomerSaveRsType"/>
 *         &lt;element name="VendorListRs" type="{FishbowlSDK}VendorListRsType"/>
 *         &lt;element name="VendorNameListRs" type="{FishbowlSDK}VendorNameListRsType"/>
 *         &lt;element name="ImportRs" type="{FishbowlSDK}ImportRsType"/>
 *         &lt;element name="ImportListRs" type="{FishbowlSDK}ImportListRsType"/>
 *         &lt;element name="ExportRs" type="{FishbowlSDK}ExportRsType"/>
 *         &lt;element name="ExportListRs" type="{FishbowlSDK}ExportListRsType"/>
 *         &lt;element name="LoginRs" type="{FishbowlSDK}LoginRsType"/>
 *         &lt;element name="CycleCountQueryRs" type="{FishbowlSDK}CycleCountQueryRsType"/>
 *         &lt;element name="CycleCountRs" type="{FishbowlSDK}CycleCountRsType"/>
 *         &lt;element name="PickQueryRs" type="{FishbowlSDK}PickQueryRsType"/>
 *         &lt;element name="GetPickRs" type="{FishbowlSDK}GetPickRsType"/>
 *         &lt;element name="SavePickRs" type="{FishbowlSDK}SavePickRsType"/>
 *         &lt;element name="PickRs" type="{FishbowlSDK}PickRsType"/>
 *         &lt;element name="FinishPickRs" type="{FishbowlSDK}FinishPickRsType"/>
 *         &lt;element name="TagInfoRs" type="{FishbowlSDK}TagInfoRsType"/>
 *         &lt;element name="YieldRs" type="{FishbowlSDK}YieldRsType"/>
 *         &lt;element name="PartQueryRs" type="{FishbowlSDK}PartQueryRsType"/>
 *         &lt;element name="PartCostRs" type="{FishbowlSDK}PartCostRsType"/>
 *         &lt;element name="ProductQueryRs" type="{FishbowlSDK}ProductQueryRsType"/>
 *         &lt;element name="ReceivingListRs" type="{FishbowlSDK}ReceivingListRsType"/>
 *         &lt;element name="ReceivingItemsRs" type="{FishbowlSDK}ReceivingItemsRsType"/>
 *         &lt;element name="ReceiveRs" type="{FishbowlSDK}ReceiveRsType"/>
 *         &lt;element name="AddInventoryRs" type="{FishbowlSDK}AddInventoryRsType"/>
 *         &lt;element name="AdjustInventoryRs" type="{FishbowlSDK}AdjustInventoryRsType"/>
 *         &lt;element name="UOMRs" type="{FishbowlSDK}UOMRsType"/>
 *         &lt;element name="LocationGroupRs" type="{FishbowlSDK}LocationGroupRsType"/>
 *         &lt;element name="DefPartLocQueryRs" type="{FishbowlSDK}DefPartLocQueryRsType"/>
 *         &lt;element name="SetDefPartLocRs" type="{FishbowlSDK}SetDefPartLocRsType"/>
 *         &lt;element name="DefLocListRs" type="{FishbowlSDK}DefLocListRsType"/>
 *         &lt;element name="POSaveRs" type="{FishbowlSDK}SavePORsType"/>
 *         &lt;element name="SaveSORs" type="{FishbowlSDK}SaveSORsType"/>
 *         &lt;element name="GetPOListRs" type="{FishbowlSDK}GetPOListRsType"/>
 *         &lt;element name="GetSOListRs" type="{FishbowlSDK}GetSOListRsType"/>
 *         &lt;element name="GetShipListRs" type="{FishbowlSDK}GetShipListRsType"/>
 *         &lt;element name="GetShipNowListRs" type="{FishbowlSDK}GetShipNowListRsType"/>
 *         &lt;element name="GetShipmentRs" type="{FishbowlSDK}GetShipmentRsType"/>
 *         &lt;element name="SaveShipmentRs" type="{FishbowlSDK}SaveShipmentRsType"/>
 *         &lt;element name="ShipRs" type="{FishbowlSDK}ShipRsType"/>
 *         &lt;element name="CarrierListRs" type="{FishbowlSDK}CarrierListRsType"/>
 *         &lt;element name="MessageRs" type="{FishbowlSDK}MessageRsType"/>
 *         &lt;element name="SetSystemPropertyRs" type="{FishbowlSDK}SetSystemPropertyRsType"/>
 *         &lt;element name="GetSystemPropertyRs" type="{FishbowlSDK}GetSystemPropertyRsType"/>
 *         &lt;element name="OpenModuleRs" type="{FishbowlSDK}OpenModuleRsType"/>
 *         &lt;element name="CustomerGetRs" type="{FishbowlSDK}CustomerGetRsType"/>
 *         &lt;element name="GetAccountBalanceRs" type="{FishbowlSDK}GetAccountBalanceRsType"/>
 *         &lt;element name="GetNextNumberRs" type="{FishbowlSDK}GetNextNumberRsType"/>
 *         &lt;element name="PartGetRs" type="{FishbowlSDK}PartGetRsType"/>
 *         &lt;element name="PartSaveRs" type="{FishbowlSDK}PartSaveRsType"/>
 *         &lt;element name="ProductSaveRs" type="{FishbowlSDK}ProductSaveRsType"/>
 *         &lt;element name="ProductGetRs" type="{FishbowlSDK}ProductGetRsType"/>
 *         &lt;element name="VendorSaveRs" type="{FishbowlSDK}VendorSaveRsType"/>
 *         &lt;element name="VendorGetRs" type="{FishbowlSDK}VendorGetRsType"/>
 *         &lt;element name="DiscountGetRs" type="{FishbowlSDK}DiscountGetRsType"/>
 *         &lt;element name="CalculateSORs" type="{FishbowlSDK}CalculateSORsType"/>
 *         &lt;element name="TaxRateGetRs" type="{FishbowlSDK}TaxRateGetRsType"/>
 *         &lt;element name="QBClassListGetRs" type="{FishbowlSDK}QBClassListGetRsType"/>
 *         &lt;element name="GetTotalInventoryRs" type="{FishbowlSDK}GetTotalInventoryRsType"/>
 *         &lt;element name="HoldPickItemRs" type="{FishbowlSDK}HoldPickItemRsType"/>
 *         &lt;element name="MakePaymentRs" type="{FishbowlSDK}MakePaymentRsType"/>
 *         &lt;element name="QuickShipRs" type="{FishbowlSDK}QuickShipRsType"/>
 *         &lt;element name="SaveDiscountRs" type="{FishbowlSDK}SaveDiscountRsType"/>
 *         &lt;element name="SaveReceiptRs" type="{FishbowlSDK}SaveReceiptRsType"/>
 *         &lt;element name="GetReceiptRs" type="{FishbowlSDK}GetReceiptRsType"/>
 *         &lt;element name="SaveTaxRateRs" type="{FishbowlSDK}SaveTaxRateRsType"/>
 *         &lt;element name="GetAccountListRs" type="{FishbowlSDK}GetAccountListRsType"/>
 *         &lt;element name="TransferOrderSaveRs" type="{FishbowlSDK}TransferOrderSaveRsType"/>
 *         &lt;element name="LoadTransferOrderRs" type="{FishbowlSDK}LoadTransferOrderRsType"/>
 *         &lt;element name="GetTransferOrderListRs" type="{FishbowlSDK}GetTransferOrderListRsType"/>
 *         &lt;element name="LoadSORs" type="{FishbowlSDK}LoadSORsType"/>
 *         &lt;element name="GetWorkOrderRs" type="{FishbowlSDK}GetWorkOrderRsType"/>
 *         &lt;element name="SaveWorkOrderRs" type="{FishbowlSDK}SaveWorkOrderRsType"/>
 *       &lt;/choice>
 *       &lt;attribute name="newMessageSetID" type="{FishbowlSDK}STRTYPE" />
 *       &lt;attribute name="statusCode" type="{FishbowlSDK}INTTYPE" />
 *       &lt;attribute name="statusMessage" type="{FishbowlSDK}STRTYPE" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tagQueryRsOrPartTagQueryRsOrLocationQueryRs"
})
@XmlRootElement(name = "FbiMsgsRs")
public class FbiMsgsRs {

    @XmlElements({
        @XmlElement(name = "TagQueryRs", type = TagQueryRsType.class),
        @XmlElement(name = "PartTagQueryRs", type = PartTagQueryRsType.class),
        @XmlElement(name = "LocationQueryRs", type = LocationQueryRsType.class),
        @XmlElement(name = "TagMoveRs", type = TagMoveRsType.class),
        @XmlElement(name = "CustomerListRs", type = CustomerListRsType.class),
        @XmlElement(name = "CustomerNameListRs", type = CustomerNameListRsType.class),
        @XmlElement(name = "CustomerSaveRs", type = CustomerSaveRsType.class),
        @XmlElement(name = "VendorListRs", type = VendorListRsType.class),
        @XmlElement(name = "VendorNameListRs", type = VendorNameListRsType.class),
        @XmlElement(name = "ImportRs", type = ImportRsType.class),
        @XmlElement(name = "ImportListRs", type = ImportListRsType.class),
        @XmlElement(name = "ExportRs", type = ExportRsType.class),
        @XmlElement(name = "ExportListRs", type = ExportListRsType.class),
        @XmlElement(name = "LoginRs", type = LoginRsType.class),
        @XmlElement(name = "CycleCountQueryRs", type = CycleCountQueryRsType.class),
        @XmlElement(name = "CycleCountRs", type = CycleCountRsType.class),
        @XmlElement(name = "PickQueryRs", type = PickQueryRsType.class),
        @XmlElement(name = "GetPickRs", type = GetPickRsType.class),
        @XmlElement(name = "SavePickRs", type = SavePickRsType.class),
        @XmlElement(name = "PickRs", type = PickRsType.class),
        @XmlElement(name = "FinishPickRs", type = FinishPickRsType.class),
        @XmlElement(name = "TagInfoRs", type = TagInfoRsType.class),
        @XmlElement(name = "YieldRs", type = YieldRsType.class),
        @XmlElement(name = "PartQueryRs", type = PartQueryRsType.class),
        @XmlElement(name = "PartCostRs", type = PartCostRsType.class),
        @XmlElement(name = "ProductQueryRs", type = ProductQueryRsType.class),
        @XmlElement(name = "ReceivingListRs", type = ReceivingListRsType.class),
        @XmlElement(name = "ReceivingItemsRs", type = ReceivingItemsRsType.class),
        @XmlElement(name = "ReceiveRs", type = ReceiveRsType.class),
        @XmlElement(name = "AddInventoryRs", type = AddInventoryRsType.class),
        @XmlElement(name = "AdjustInventoryRs", type = AdjustInventoryRsType.class),
        @XmlElement(name = "UOMRs", type = UOMRsType.class),
        @XmlElement(name = "LocationGroupRs", type = LocationGroupRsType.class),
        @XmlElement(name = "DefPartLocQueryRs", type = DefPartLocQueryRsType.class),
        @XmlElement(name = "SetDefPartLocRs", type = SetDefPartLocRsType.class),
        @XmlElement(name = "DefLocListRs", type = DefLocListRsType.class),
        @XmlElement(name = "POSaveRs", type = SavePORsType.class),
        @XmlElement(name = "SaveSORs", type = SaveSORsType.class),
        @XmlElement(name = "GetPOListRs", type = GetPOListRsType.class),
        @XmlElement(name = "GetSOListRs", type = GetSOListRsType.class),
        @XmlElement(name = "GetShipListRs", type = GetShipListRsType.class),
        @XmlElement(name = "GetShipNowListRs", type = GetShipNowListRsType.class),
        @XmlElement(name = "GetShipmentRs", type = GetShipmentRsType.class),
        @XmlElement(name = "SaveShipmentRs", type = SaveShipmentRsType.class),
        @XmlElement(name = "ShipRs", type = ShipRsType.class),
        @XmlElement(name = "CarrierListRs", type = CarrierListRsType.class),
        @XmlElement(name = "MessageRs", type = MessageRsType.class),
        @XmlElement(name = "SetSystemPropertyRs", type = SetSystemPropertyRsType.class),
        @XmlElement(name = "GetSystemPropertyRs", type = GetSystemPropertyRsType.class),
        @XmlElement(name = "OpenModuleRs", type = OpenModuleRsType.class),
        @XmlElement(name = "CustomerGetRs", type = CustomerGetRsType.class),
        @XmlElement(name = "GetAccountBalanceRs", type = GetAccountBalanceRsType.class),
        @XmlElement(name = "GetNextNumberRs", type = GetNextNumberRsType.class),
        @XmlElement(name = "PartGetRs", type = PartGetRsType.class),
        @XmlElement(name = "PartSaveRs", type = PartSaveRsType.class),
        @XmlElement(name = "ProductSaveRs", type = ProductSaveRsType.class),
        @XmlElement(name = "ProductGetRs", type = ProductGetRsType.class),
        @XmlElement(name = "VendorSaveRs", type = VendorSaveRsType.class),
        @XmlElement(name = "VendorGetRs", type = VendorGetRsType.class),
        @XmlElement(name = "DiscountGetRs", type = DiscountGetRsType.class),
        @XmlElement(name = "CalculateSORs", type = CalculateSORsType.class),
        @XmlElement(name = "TaxRateGetRs", type = TaxRateGetRsType.class),
        @XmlElement(name = "QBClassListGetRs", type = QBClassListGetRsType.class),
        @XmlElement(name = "GetTotalInventoryRs", type = GetTotalInventoryRsType.class),
        @XmlElement(name = "HoldPickItemRs", type = HoldPickItemRsType.class),
        @XmlElement(name = "MakePaymentRs", type = MakePaymentRsType.class),
        @XmlElement(name = "QuickShipRs", type = QuickShipRsType.class),
        @XmlElement(name = "SaveDiscountRs", type = SaveDiscountRsType.class),
        @XmlElement(name = "SaveReceiptRs", type = SaveReceiptRsType.class),
        @XmlElement(name = "GetReceiptRs", type = GetReceiptRsType.class),
        @XmlElement(name = "SaveTaxRateRs", type = SaveTaxRateRsType.class),
        @XmlElement(name = "GetAccountListRs", type = GetAccountListRsType.class),
        @XmlElement(name = "TransferOrderSaveRs", type = TransferOrderSaveRsType.class),
        @XmlElement(name = "LoadTransferOrderRs", type = LoadTransferOrderRsType.class),
        @XmlElement(name = "GetTransferOrderListRs", type = GetTransferOrderListRsType.class),
        @XmlElement(name = "LoadSORs", type = LoadSORsType.class),
        @XmlElement(name = "GetWorkOrderRs", type = GetWorkOrderRsType.class),
        @XmlElement(name = "SaveWorkOrderRs", type = SaveWorkOrderRsType.class)
    })
    protected List<Object> tagQueryRsOrPartTagQueryRsOrLocationQueryRs;
    @XmlAttribute(name = "newMessageSetID")
    protected String newMessageSetID;
    @XmlAttribute(name = "statusCode")
    protected BigInteger statusCode;
    @XmlAttribute(name = "statusMessage")
    protected String statusMessage;

    /**
     * Gets the value of the tagQueryRsOrPartTagQueryRsOrLocationQueryRs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tagQueryRsOrPartTagQueryRsOrLocationQueryRs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTagQueryRsOrPartTagQueryRsOrLocationQueryRs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TagQueryRsType }
     * {@link PartTagQueryRsType }
     * {@link LocationQueryRsType }
     * {@link TagMoveRsType }
     * {@link CustomerListRsType }
     * {@link CustomerNameListRsType }
     * {@link CustomerSaveRsType }
     * {@link VendorListRsType }
     * {@link VendorNameListRsType }
     * {@link ImportRsType }
     * {@link ImportListRsType }
     * {@link ExportRsType }
     * {@link ExportListRsType }
     * {@link LoginRsType }
     * {@link CycleCountQueryRsType }
     * {@link CycleCountRsType }
     * {@link PickQueryRsType }
     * {@link GetPickRsType }
     * {@link SavePickRsType }
     * {@link PickRsType }
     * {@link FinishPickRsType }
     * {@link TagInfoRsType }
     * {@link YieldRsType }
     * {@link PartQueryRsType }
     * {@link PartCostRsType }
     * {@link ProductQueryRsType }
     * {@link ReceivingListRsType }
     * {@link ReceivingItemsRsType }
     * {@link ReceiveRsType }
     * {@link AddInventoryRsType }
     * {@link AdjustInventoryRsType }
     * {@link UOMRsType }
     * {@link LocationGroupRsType }
     * {@link DefPartLocQueryRsType }
     * {@link SetDefPartLocRsType }
     * {@link DefLocListRsType }
     * {@link SavePORsType }
     * {@link SaveSORsType }
     * {@link GetPOListRsType }
     * {@link GetSOListRsType }
     * {@link GetShipListRsType }
     * {@link GetShipNowListRsType }
     * {@link GetShipmentRsType }
     * {@link SaveShipmentRsType }
     * {@link ShipRsType }
     * {@link CarrierListRsType }
     * {@link MessageRsType }
     * {@link SetSystemPropertyRsType }
     * {@link GetSystemPropertyRsType }
     * {@link OpenModuleRsType }
     * {@link CustomerGetRsType }
     * {@link GetAccountBalanceRsType }
     * {@link GetNextNumberRsType }
     * {@link PartGetRsType }
     * {@link PartSaveRsType }
     * {@link ProductSaveRsType }
     * {@link ProductGetRsType }
     * {@link VendorSaveRsType }
     * {@link VendorGetRsType }
     * {@link DiscountGetRsType }
     * {@link CalculateSORsType }
     * {@link TaxRateGetRsType }
     * {@link QBClassListGetRsType }
     * {@link GetTotalInventoryRsType }
     * {@link HoldPickItemRsType }
     * {@link MakePaymentRsType }
     * {@link QuickShipRsType }
     * {@link SaveDiscountRsType }
     * {@link SaveReceiptRsType }
     * {@link GetReceiptRsType }
     * {@link SaveTaxRateRsType }
     * {@link GetAccountListRsType }
     * {@link TransferOrderSaveRsType }
     * {@link LoadTransferOrderRsType }
     * {@link GetTransferOrderListRsType }
     * {@link LoadSORsType }
     * {@link GetWorkOrderRsType }
     * {@link SaveWorkOrderRsType }
     * 
     * 
     */
    public List<Object> getTagQueryRsOrPartTagQueryRsOrLocationQueryRs() {
        if (tagQueryRsOrPartTagQueryRsOrLocationQueryRs == null) {
            tagQueryRsOrPartTagQueryRsOrLocationQueryRs = new ArrayList<Object>();
        }
        return this.tagQueryRsOrPartTagQueryRsOrLocationQueryRs;
    }

    /**
     * Gets the value of the newMessageSetID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewMessageSetID() {
        return newMessageSetID;
    }

    /**
     * Sets the value of the newMessageSetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewMessageSetID(String value) {
        this.newMessageSetID = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatusCode(BigInteger value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusMessage() {
        return statusMessage;
    }

    /**
     * Sets the value of the statusMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusMessage(String value) {
        this.statusMessage = value;
    }

}
