//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{FishbowlSDK}Ticket"/>
 *         &lt;choice>
 *           &lt;element ref="{FishbowlSDK}FbiMsgsRq"/>
 *           &lt;element ref="{FishbowlSDK}FbiMsgsRs"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ticket",
    "fbiMsgsRq",
    "fbiMsgsRs"
})
@XmlRootElement(name = "FbiXml")
public class FbiXml {

    @XmlElement(name = "Ticket", required = true)
    protected Ticket ticket;
    @XmlElement(name = "FbiMsgsRq")
    protected FbiMsgsRq fbiMsgsRq;
    @XmlElement(name = "FbiMsgsRs")
    protected FbiMsgsRs fbiMsgsRs;

    /**
     * Gets the value of the ticket property.
     * 
     * @return
     *     possible object is
     *     {@link Ticket }
     *     
     */
    public Ticket getTicket() {
        return ticket;
    }

    /**
     * Sets the value of the ticket property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ticket }
     *     
     */
    public void setTicket(Ticket value) {
        this.ticket = value;
    }

    /**
     * Gets the value of the fbiMsgsRq property.
     * 
     * @return
     *     possible object is
     *     {@link FbiMsgsRq }
     *     
     */
    public FbiMsgsRq getFbiMsgsRq() {
        return fbiMsgsRq;
    }

    /**
     * Sets the value of the fbiMsgsRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link FbiMsgsRq }
     *     
     */
    public void setFbiMsgsRq(FbiMsgsRq value) {
        this.fbiMsgsRq = value;
    }

    /**
     * Gets the value of the fbiMsgsRs property.
     * 
     * @return
     *     possible object is
     *     {@link FbiMsgsRs }
     *     
     */
    public FbiMsgsRs getFbiMsgsRs() {
        return fbiMsgsRs;
    }

    /**
     * Sets the value of the fbiMsgsRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link FbiMsgsRs }
     *     
     */
    public void setFbiMsgsRs(FbiMsgsRs value) {
        this.fbiMsgsRs = value;
    }

}
