//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetShipListRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetShipListRqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StartRecord" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="RecordCount" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="OrderNumber" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="OrderTypeID" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="StatusID" type="{FishbowlSDK}INTTYPE"/>
 *         &lt;element name="LocationGroup" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="Carrier" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetShipListRqType", propOrder = {
    "startRecord",
    "recordCount",
    "orderNumber",
    "orderTypeID",
    "statusID",
    "locationGroup",
    "carrier"
})
public class GetShipListRqType {

    @XmlElement(name = "StartRecord")
    protected BigInteger startRecord;
    @XmlElement(name = "RecordCount")
    protected BigInteger recordCount;
    @XmlElement(name = "OrderNumber")
    protected BigInteger orderNumber;
    @XmlElement(name = "OrderTypeID")
    protected BigInteger orderTypeID;
    @XmlElement(name = "StatusID", required = true)
    protected BigInteger statusID;
    @XmlElement(name = "LocationGroup", required = true)
    protected String locationGroup;
    @XmlElement(name = "Carrier")
    protected BigInteger carrier;

    /**
     * Gets the value of the startRecord property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStartRecord() {
        return startRecord;
    }

    /**
     * Sets the value of the startRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStartRecord(BigInteger value) {
        this.startRecord = value;
    }

    /**
     * Gets the value of the recordCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecordCount() {
        return recordCount;
    }

    /**
     * Sets the value of the recordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecordCount(BigInteger value) {
        this.recordCount = value;
    }

    /**
     * Gets the value of the orderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderNumber() {
        return orderNumber;
    }

    /**
     * Sets the value of the orderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderNumber(BigInteger value) {
        this.orderNumber = value;
    }

    /**
     * Gets the value of the orderTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderTypeID() {
        return orderTypeID;
    }

    /**
     * Sets the value of the orderTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderTypeID(BigInteger value) {
        this.orderTypeID = value;
    }

    /**
     * Gets the value of the statusID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatusID() {
        return statusID;
    }

    /**
     * Sets the value of the statusID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatusID(BigInteger value) {
        this.statusID = value;
    }

    /**
     * Gets the value of the locationGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationGroup() {
        return locationGroup;
    }

    /**
     * Sets the value of the locationGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationGroup(String value) {
        this.locationGroup = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCarrier(BigInteger value) {
        this.carrier = value;
    }

}
