//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{FishbowlSDK}DB_ID"/>
 *         &lt;element ref="{FishbowlSDK}Description" minOccurs="0"/>
 *         &lt;element name="KitItemType" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element ref="{FishbowlSDK}Product" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}TaxRate" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}Discount" minOccurs="0"/>
 *         &lt;element name="ParentProductID" type="{FishbowlSDK}DB_ID"/>
 *         &lt;element name="QtyPriceAdjustment" type="{FishbowlSDK}PRICETYPE" minOccurs="0"/>
 *         &lt;element name="SortOrder" type="{FishbowlSDK}INTTYPE"/>
 *         &lt;element name="DefaultQty" type="{FishbowlSDK}QUANTYPE"/>
 *         &lt;element name="MinQty" type="{FishbowlSDK}QUANTYPE" minOccurs="0"/>
 *         &lt;element name="MaxQty" type="{FishbowlSDK}QUANTYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}UOM"/>
 *         &lt;element name="KitType" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="SOItemType" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="Note" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="DateCreated" type="{FishbowlSDK}DATETIMETYPE" minOccurs="0"/>
 *         &lt;element name="DateModified" type="{FishbowlSDK}DATETIMETYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}KitOption" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "description",
    "kitItemType",
    "product",
    "taxRate",
    "discount",
    "parentProductID",
    "qtyPriceAdjustment",
    "sortOrder",
    "defaultQty",
    "minQty",
    "maxQty",
    "uom",
    "kitType",
    "soItemType",
    "note",
    "dateCreated",
    "dateModified",
    "kitOption"
})
@XmlRootElement(name = "KitItem")
public class KitItem {

    @XmlElement(name = "ID", required = true)
    protected BigInteger id;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "KitItemType", required = true)
    protected String kitItemType;
    @XmlElement(name = "Product")
    protected Product product;
    @XmlElement(name = "TaxRate")
    protected TaxRate taxRate;
    @XmlElement(name = "Discount")
    protected Discount discount;
    @XmlElement(name = "ParentProductID", required = true)
    protected BigInteger parentProductID;
    @XmlElement(name = "QtyPriceAdjustment")
    protected String qtyPriceAdjustment;
    @XmlElement(name = "SortOrder", required = true)
    protected BigInteger sortOrder;
    @XmlElement(name = "DefaultQty", required = true)
    protected String defaultQty;
    @XmlElement(name = "MinQty")
    protected String minQty;
    @XmlElement(name = "MaxQty")
    protected String maxQty;
    @XmlElement(name = "UOM", required = true)
    protected UOM uom;
    @XmlElement(name = "KitType", required = true)
    protected String kitType;
    @XmlElement(name = "SOItemType", required = true)
    protected String soItemType;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "DateCreated")
    protected String dateCreated;
    @XmlElement(name = "DateModified")
    protected String dateModified;
    @XmlElement(name = "KitOption")
    protected List<KitOption> kitOption;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the kitItemType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKitItemType() {
        return kitItemType;
    }

    /**
     * Sets the value of the kitItemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKitItemType(String value) {
        this.kitItemType = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link Product }
     *     
     */
    public Product getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link Product }
     *     
     */
    public void setProduct(Product value) {
        this.product = value;
    }

    /**
     * Gets the value of the taxRate property.
     * 
     * @return
     *     possible object is
     *     {@link TaxRate }
     *     
     */
    public TaxRate getTaxRate() {
        return taxRate;
    }

    /**
     * Sets the value of the taxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxRate }
     *     
     */
    public void setTaxRate(TaxRate value) {
        this.taxRate = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link Discount }
     *     
     */
    public Discount getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Discount }
     *     
     */
    public void setDiscount(Discount value) {
        this.discount = value;
    }

    /**
     * Gets the value of the parentProductID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParentProductID() {
        return parentProductID;
    }

    /**
     * Sets the value of the parentProductID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParentProductID(BigInteger value) {
        this.parentProductID = value;
    }

    /**
     * Gets the value of the qtyPriceAdjustment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtyPriceAdjustment() {
        return qtyPriceAdjustment;
    }

    /**
     * Sets the value of the qtyPriceAdjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtyPriceAdjustment(String value) {
        this.qtyPriceAdjustment = value;
    }

    /**
     * Gets the value of the sortOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the value of the sortOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSortOrder(BigInteger value) {
        this.sortOrder = value;
    }

    /**
     * Gets the value of the defaultQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultQty() {
        return defaultQty;
    }

    /**
     * Sets the value of the defaultQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultQty(String value) {
        this.defaultQty = value;
    }

    /**
     * Gets the value of the minQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinQty() {
        return minQty;
    }

    /**
     * Sets the value of the minQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinQty(String value) {
        this.minQty = value;
    }

    /**
     * Gets the value of the maxQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxQty() {
        return maxQty;
    }

    /**
     * Sets the value of the maxQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxQty(String value) {
        this.maxQty = value;
    }

    /**
     * Gets the value of the uom property.
     * 
     * @return
     *     possible object is
     *     {@link UOM }
     *     
     */
    public UOM getUOM() {
        return uom;
    }

    /**
     * Sets the value of the uom property.
     * 
     * @param value
     *     allowed object is
     *     {@link UOM }
     *     
     */
    public void setUOM(UOM value) {
        this.uom = value;
    }

    /**
     * Gets the value of the kitType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKitType() {
        return kitType;
    }

    /**
     * Sets the value of the kitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKitType(String value) {
        this.kitType = value;
    }

    /**
     * Gets the value of the soItemType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOItemType() {
        return soItemType;
    }

    /**
     * Sets the value of the soItemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOItemType(String value) {
        this.soItemType = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateCreated(String value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the dateModified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateModified() {
        return dateModified;
    }

    /**
     * Sets the value of the dateModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateModified(String value) {
        this.dateModified = value;
    }

    /**
     * Gets the value of the kitOption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kitOption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKitOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KitOption }
     * 
     * 
     */
    public List<KitOption> getKitOption() {
        if (kitOption == null) {
            kitOption = new ArrayList<KitOption>();
        }
        return this.kitOption;
    }

}
