//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{FishbowlSDK}LocationID"/>
 *         &lt;element name="TypeID" type="{FishbowlSDK}INTTYPE"/>
 *         &lt;element ref="{FishbowlSDK}ParentID" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}Name"/>
 *         &lt;element ref="{FishbowlSDK}Description" minOccurs="0"/>
 *         &lt;element name="CountedAsAvailable" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="Default" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="Active" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="Pickable" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="Receivable" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}LocationGroupID"/>
 *         &lt;element name="LocationGroupName" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="EnforceTracking" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="SortOrder" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "locationID",
    "typeID",
    "parentID",
    "name",
    "description",
    "countedAsAvailable",
    "_default",
    "active",
    "pickable",
    "receivable",
    "locationGroupID",
    "locationGroupName",
    "enforceTracking",
    "sortOrder"
})
@XmlRootElement(name = "Location")
public class Location {

    @XmlElement(name = "LocationID", required = true)
    protected BigInteger locationID;
    @XmlElement(name = "TypeID", required = true)
    protected BigInteger typeID;
    @XmlElement(name = "ParentID")
    protected BigInteger parentID;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "CountedAsAvailable")
    protected Boolean countedAsAvailable;
    @XmlElement(name = "Default")
    protected Boolean _default;
    @XmlElement(name = "Active")
    protected Boolean active;
    @XmlElement(name = "Pickable")
    protected Boolean pickable;
    @XmlElement(name = "Receivable")
    protected Boolean receivable;
    @XmlElement(name = "LocationGroupID", required = true)
    protected BigInteger locationGroupID;
    @XmlElement(name = "LocationGroupName")
    protected String locationGroupName;
    @XmlElement(name = "EnforceTracking")
    protected Boolean enforceTracking;
    @XmlElement(name = "SortOrder")
    protected BigInteger sortOrder;

    /**
     * Gets the value of the locationID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocationID() {
        return locationID;
    }

    /**
     * Sets the value of the locationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocationID(BigInteger value) {
        this.locationID = value;
    }

    /**
     * Gets the value of the typeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTypeID() {
        return typeID;
    }

    /**
     * Sets the value of the typeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTypeID(BigInteger value) {
        this.typeID = value;
    }

    /**
     * Gets the value of the parentID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParentID() {
        return parentID;
    }

    /**
     * Sets the value of the parentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParentID(BigInteger value) {
        this.parentID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the countedAsAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCountedAsAvailable() {
        return countedAsAvailable;
    }

    /**
     * Sets the value of the countedAsAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCountedAsAvailable(Boolean value) {
        this.countedAsAvailable = value;
    }

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefault(Boolean value) {
        this._default = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActive(Boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the pickable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPickable() {
        return pickable;
    }

    /**
     * Sets the value of the pickable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPickable(Boolean value) {
        this.pickable = value;
    }

    /**
     * Gets the value of the receivable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReceivable() {
        return receivable;
    }

    /**
     * Sets the value of the receivable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReceivable(Boolean value) {
        this.receivable = value;
    }

    /**
     * Gets the value of the locationGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocationGroupID() {
        return locationGroupID;
    }

    /**
     * Sets the value of the locationGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocationGroupID(BigInteger value) {
        this.locationGroupID = value;
    }

    /**
     * Gets the value of the locationGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationGroupName() {
        return locationGroupName;
    }

    /**
     * Sets the value of the locationGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationGroupName(String value) {
        this.locationGroupName = value;
    }

    /**
     * Gets the value of the enforceTracking property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnforceTracking() {
        return enforceTracking;
    }

    /**
     * Sets the value of the enforceTracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnforceTracking(Boolean value) {
        this.enforceTracking = value;
    }

    /**
     * Gets the value of the sortOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the value of the sortOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSortOrder(BigInteger value) {
        this.sortOrder = value;
    }

}
