//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.abhi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PriorityID_QNAME = new QName("FishbowlSDK", "PriorityID");
    private final static QName _VendorID_QNAME = new QName("FishbowlSDK", "VendorID");
    private final static QName _DateLastModified_QNAME = new QName("FishbowlSDK", "DateLastModified");
    private final static QName _PartID_QNAME = new QName("FishbowlSDK", "PartID");
    private final static QName _SortID_QNAME = new QName("FishbowlSDK", "SortID");
    private final static QName _IsActive_QNAME = new QName("FishbowlSDK", "IsActive");
    private final static QName _Date_QNAME = new QName("FishbowlSDK", "Date");
    private final static QName _ProductNum_QNAME = new QName("FishbowlSDK", "ProductNum");
    private final static QName _QuantityToFulfill_QNAME = new QName("FishbowlSDK", "QuantityToFulfill");
    private final static QName _Rev_QNAME = new QName("FishbowlSDK", "Rev");
    private final static QName _UPC_QNAME = new QName("FishbowlSDK", "UPC");
    private final static QName _TimeModified_QNAME = new QName("FishbowlSDK", "TimeModified");
    private final static QName _LotNum_QNAME = new QName("FishbowlSDK", "LotNum");
    private final static QName _Barcode_QNAME = new QName("FishbowlSDK", "Barcode");
    private final static QName _CogsAccountID_QNAME = new QName("FishbowlSDK", "CogsAccountID");
    private final static QName _DateFinished_QNAME = new QName("FishbowlSDK", "DateFinished");
    private final static QName _QBClassID_QNAME = new QName("FishbowlSDK", "QBClassID");
    private final static QName _StatusID_QNAME = new QName("FishbowlSDK", "StatusID");
    private final static QName _DefPaymentTermsID_QNAME = new QName("FishbowlSDK", "DefPaymentTermsID");
    private final static QName _MOItemID_QNAME = new QName("FishbowlSDK", "MOItemID");
    private final static QName _CustomerID_QNAME = new QName("FishbowlSDK", "CustomerID");
    private final static QName _QtyScrapped_QNAME = new QName("FishbowlSDK", "QtyScrapped");
    private final static QName _DefShipTermsID_QNAME = new QName("FishbowlSDK", "DefShipTermsID");
    private final static QName _DateStarted_QNAME = new QName("FishbowlSDK", "DateStarted");
    private final static QName _PartNum_QNAME = new QName("FishbowlSDK", "PartNum");
    private final static QName _Number_QNAME = new QName("FishbowlSDK", "Number");
    private final static QName _AccountID_QNAME = new QName("FishbowlSDK", "AccountID");
    private final static QName _AccountingHash_QNAME = new QName("FishbowlSDK", "AccountingHash");
    private final static QName _Num_QNAME = new QName("FishbowlSDK", "Num");
    private final static QName _AccountingID_QNAME = new QName("FishbowlSDK", "AccountingID");
    private final static QName _DateCreated_QNAME = new QName("FishbowlSDK", "DateCreated");
    private final static QName _PartClassID_QNAME = new QName("FishbowlSDK", "PartClassID");
    private final static QName _Manufacturer_QNAME = new QName("FishbowlSDK", "Manufacturer");
    private final static QName _LastChangedUser_QNAME = new QName("FishbowlSDK", "LastChangedUser");
    private final static QName _LocationID_QNAME = new QName("FishbowlSDK", "LocationID");
    private final static QName _TagNum_QNAME = new QName("FishbowlSDK", "TagNum");
    private final static QName _QuantityFulfilled_QNAME = new QName("FishbowlSDK", "QuantityFulfilled");
    private final static QName _CarrierID_QNAME = new QName("FishbowlSDK", "CarrierID");
    private final static QName _TaxRateID_QNAME = new QName("FishbowlSDK", "TaxRateID");
    private final static QName _Type_QNAME = new QName("FishbowlSDK", "Type");
    private final static QName _UserName_QNAME = new QName("FishbowlSDK", "UserName");
    private final static QName _TagID_QNAME = new QName("FishbowlSDK", "TagID");
    private final static QName _TypeID_QNAME = new QName("FishbowlSDK", "TypeID");
    private final static QName _WOID_QNAME = new QName("FishbowlSDK", "WOID");
    private final static QName _QuantityPicked_QNAME = new QName("FishbowlSDK", "QuantityPicked");
    private final static QName _DateScheduledToStart_QNAME = new QName("FishbowlSDK", "DateScheduledToStart");
    private final static QName _Status_QNAME = new QName("FishbowlSDK", "Status");
    private final static QName _Name_QNAME = new QName("FishbowlSDK", "Name");
    private final static QName _Info_QNAME = new QName("FishbowlSDK", "Info");
    private final static QName _ABCCode_QNAME = new QName("FishbowlSDK", "ABCCode");
    private final static QName _LocationGroupID_QNAME = new QName("FishbowlSDK", "LocationGroupID");
    private final static QName _EditSequence_QNAME = new QName("FishbowlSDK", "EditSequence");
    private final static QName _DateLastIssued_QNAME = new QName("FishbowlSDK", "DateLastIssued");
    private final static QName _ShippingCost_QNAME = new QName("FishbowlSDK", "ShippingCost");
    private final static QName _Quantity_QNAME = new QName("FishbowlSDK", "Quantity");
    private final static QName _Description_QNAME = new QName("FishbowlSDK", "Description");
    private final static QName _DateFirstShipped_QNAME = new QName("FishbowlSDK", "DateFirstShipped");
    private final static QName _QtyToFulfill_QNAME = new QName("FishbowlSDK", "QtyToFulfill");
    private final static QName _DateConfirmed_QNAME = new QName("FishbowlSDK", "DateConfirmed");
    private final static QName _DateScheduled_QNAME = new QName("FishbowlSDK", "DateScheduled");
    private final static QName _QtyUsed_QNAME = new QName("FishbowlSDK", "QtyUsed");
    private final static QName _Note_QNAME = new QName("FishbowlSDK", "Note");
    private final static QName _Priority_QNAME = new QName("FishbowlSDK", "Priority");
    private final static QName _ParentID_QNAME = new QName("FishbowlSDK", "ParentID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.abhi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Part }
     * 
     */
    public Part createPart() {
        return new Part();
    }

    /**
     * Create an instance of {@link WOItem }
     * 
     */
    public WOItem createWOItem() {
        return new WOItem();
    }

    /**
     * Create an instance of {@link WO }
     * 
     */
    public WO createWO() {
        return new WO();
    }

    /**
     * Create an instance of {@link com.abhi.User }
     * 
     */
    public com.abhi.User createUser() {
        return new com.abhi.User();
    }

    /**
     * Create an instance of {@link Rows }
     * 
     */
    public Rows createRows() {
        return new Rows();
    }

    /**
     * Create an instance of {@link Customers }
     * 
     */
    public Customers createCustomers() {
        return new Customers();
    }

    /**
     * Create an instance of {@link VendorPartNumber }
     * 
     */
    public VendorPartNumber createVendorPartNumber() {
        return new VendorPartNumber();
    }

    /**
     * Create an instance of {@link LinkedOrders }
     * 
     */
    public LinkedOrders createLinkedOrders() {
        return new LinkedOrders();
    }

    /**
     * Create an instance of {@link RMAItemLink }
     * 
     */
    public RMAItemLink createRMAItemLink() {
        return new RMAItemLink();
    }

    /**
     * Create an instance of {@link PartTracking }
     * 
     */
    public PartTracking createPartTracking() {
        return new PartTracking();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link Vendors }
     * 
     */
    public Vendors createVendors() {
        return new Vendors();
    }

    /**
     * Create an instance of {@link SerialBox }
     * 
     */
    public SerialBox createSerialBox() {
        return new SerialBox();
    }

    /**
     * Create an instance of {@link SerialNumList }
     * 
     */
    public SerialNumList createSerialNumList() {
        return new SerialNumList();
    }

    /**
     * Create an instance of {@link SerialNum }
     * 
     */
    public SerialNum createSerialNum() {
        return new SerialNum();
    }

    /**
     * Create an instance of {@link SalesOrderItem }
     * 
     */
    public SalesOrderItem createSalesOrderItem() {
        return new SalesOrderItem();
    }

    /**
     * Create an instance of {@link Ticket }
     * 
     */
    public Ticket createTicket() {
        return new Ticket();
    }

    /**
     * Create an instance of {@link CustomListItems }
     * 
     */
    public CustomListItems createCustomListItems() {
        return new CustomListItems();
    }

    /**
     * Create an instance of {@link CustomListItem }
     * 
     */
    public CustomListItem createCustomListItem() {
        return new CustomListItem();
    }

    /**
     * Create an instance of {@link FbiXml }
     * 
     */
    public FbiXml createFbiXml() {
        return new FbiXml();
    }

    /**
     * Create an instance of {@link FbiMsgsRq }
     * 
     */
    public FbiMsgsRq createFbiMsgsRq() {
        return new FbiMsgsRq();
    }

    /**
     * Create an instance of {@link TagQueryRqType }
     * 
     */
    public TagQueryRqType createTagQueryRqType() {
        return new TagQueryRqType();
    }

    /**
     * Create an instance of {@link LocationQueryRqType }
     * 
     */
    public LocationQueryRqType createLocationQueryRqType() {
        return new LocationQueryRqType();
    }

    /**
     * Create an instance of {@link TagMoveRqType }
     * 
     */
    public TagMoveRqType createTagMoveRqType() {
        return new TagMoveRqType();
    }

    /**
     * Create an instance of {@link CustomerListRqType }
     * 
     */
    public CustomerListRqType createCustomerListRqType() {
        return new CustomerListRqType();
    }

    /**
     * Create an instance of {@link CustomerNameListRqType }
     * 
     */
    public CustomerNameListRqType createCustomerNameListRqType() {
        return new CustomerNameListRqType();
    }

    /**
     * Create an instance of {@link CustomerSaveRqType }
     * 
     */
    public CustomerSaveRqType createCustomerSaveRqType() {
        return new CustomerSaveRqType();
    }

    /**
     * Create an instance of {@link VendorListRqType }
     * 
     */
    public VendorListRqType createVendorListRqType() {
        return new VendorListRqType();
    }

    /**
     * Create an instance of {@link VendorNameListRqType }
     * 
     */
    public VendorNameListRqType createVendorNameListRqType() {
        return new VendorNameListRqType();
    }

    /**
     * Create an instance of {@link ImportRqType }
     * 
     */
    public ImportRqType createImportRqType() {
        return new ImportRqType();
    }

    /**
     * Create an instance of {@link ImportListRqType }
     * 
     */
    public ImportListRqType createImportListRqType() {
        return new ImportListRqType();
    }

    /**
     * Create an instance of {@link ExportRqType }
     * 
     */
    public ExportRqType createExportRqType() {
        return new ExportRqType();
    }

    /**
     * Create an instance of {@link ExportListRqType }
     * 
     */
    public ExportListRqType createExportListRqType() {
        return new ExportListRqType();
    }

    /**
     * Create an instance of {@link PartTagQueryRqType }
     * 
     */
    public PartTagQueryRqType createPartTagQueryRqType() {
        return new PartTagQueryRqType();
    }

    /**
     * Create an instance of {@link DefPartLocQueryRqType }
     * 
     */
    public DefPartLocQueryRqType createDefPartLocQueryRqType() {
        return new DefPartLocQueryRqType();
    }

    /**
     * Create an instance of {@link SetDefPartLocRqType }
     * 
     */
    public SetDefPartLocRqType createSetDefPartLocRqType() {
        return new SetDefPartLocRqType();
    }

    /**
     * Create an instance of {@link LoginRqType }
     * 
     */
    public LoginRqType createLoginRqType() {
        return new LoginRqType();
    }

    /**
     * Create an instance of {@link CycleCountQueryRqType }
     * 
     */
    public CycleCountQueryRqType createCycleCountQueryRqType() {
        return new CycleCountQueryRqType();
    }

    /**
     * Create an instance of {@link CycleCountRqType }
     * 
     */
    public CycleCountRqType createCycleCountRqType() {
        return new CycleCountRqType();
    }

    /**
     * Create an instance of {@link PickQueryRqType }
     * 
     */
    public PickQueryRqType createPickQueryRqType() {
        return new PickQueryRqType();
    }

    /**
     * Create an instance of {@link GetPickRqType }
     * 
     */
    public GetPickRqType createGetPickRqType() {
        return new GetPickRqType();
    }

    /**
     * Create an instance of {@link SavePickRqType }
     * 
     */
    public SavePickRqType createSavePickRqType() {
        return new SavePickRqType();
    }

    /**
     * Create an instance of {@link PickRqType }
     * 
     */
    public PickRqType createPickRqType() {
        return new PickRqType();
    }

    /**
     * Create an instance of {@link FinishPickRqType }
     * 
     */
    public FinishPickRqType createFinishPickRqType() {
        return new FinishPickRqType();
    }

    /**
     * Create an instance of {@link TagInfoRqType }
     * 
     */
    public TagInfoRqType createTagInfoRqType() {
        return new TagInfoRqType();
    }

    /**
     * Create an instance of {@link YieldRqType }
     * 
     */
    public YieldRqType createYieldRqType() {
        return new YieldRqType();
    }

    /**
     * Create an instance of {@link PartQueryRqType }
     * 
     */
    public PartQueryRqType createPartQueryRqType() {
        return new PartQueryRqType();
    }

    /**
     * Create an instance of {@link PartCostRqType }
     * 
     */
    public PartCostRqType createPartCostRqType() {
        return new PartCostRqType();
    }

    /**
     * Create an instance of {@link ProductQueryRqType }
     * 
     */
    public ProductQueryRqType createProductQueryRqType() {
        return new ProductQueryRqType();
    }

    /**
     * Create an instance of {@link ReceivingListRqType }
     * 
     */
    public ReceivingListRqType createReceivingListRqType() {
        return new ReceivingListRqType();
    }

    /**
     * Create an instance of {@link ReceivingItemsRqType }
     * 
     */
    public ReceivingItemsRqType createReceivingItemsRqType() {
        return new ReceivingItemsRqType();
    }

    /**
     * Create an instance of {@link ReceiveRqType }
     * 
     */
    public ReceiveRqType createReceiveRqType() {
        return new ReceiveRqType();
    }

    /**
     * Create an instance of {@link AddInventoryRqType }
     * 
     */
    public AddInventoryRqType createAddInventoryRqType() {
        return new AddInventoryRqType();
    }

    /**
     * Create an instance of {@link AdjustInventoryRqType }
     * 
     */
    public AdjustInventoryRqType createAdjustInventoryRqType() {
        return new AdjustInventoryRqType();
    }

    /**
     * Create an instance of {@link UOMRqType }
     * 
     */
    public UOMRqType createUOMRqType() {
        return new UOMRqType();
    }

    /**
     * Create an instance of {@link LocationGroupRqType }
     * 
     */
    public LocationGroupRqType createLocationGroupRqType() {
        return new LocationGroupRqType();
    }

    /**
     * Create an instance of {@link DefLocListRqType }
     * 
     */
    public DefLocListRqType createDefLocListRqType() {
        return new DefLocListRqType();
    }

    /**
     * Create an instance of {@link SavePORqType }
     * 
     */
    public SavePORqType createSavePORqType() {
        return new SavePORqType();
    }

    /**
     * Create an instance of {@link SaveSORqType }
     * 
     */
    public SaveSORqType createSaveSORqType() {
        return new SaveSORqType();
    }

    /**
     * Create an instance of {@link GetPOListRqType }
     * 
     */
    public GetPOListRqType createGetPOListRqType() {
        return new GetPOListRqType();
    }

    /**
     * Create an instance of {@link GetSOListRqType }
     * 
     */
    public GetSOListRqType createGetSOListRqType() {
        return new GetSOListRqType();
    }

    /**
     * Create an instance of {@link GetShipListRqType }
     * 
     */
    public GetShipListRqType createGetShipListRqType() {
        return new GetShipListRqType();
    }

    /**
     * Create an instance of {@link GetShipNowListRqType }
     * 
     */
    public GetShipNowListRqType createGetShipNowListRqType() {
        return new GetShipNowListRqType();
    }

    /**
     * Create an instance of {@link GetShipmentRqType }
     * 
     */
    public GetShipmentRqType createGetShipmentRqType() {
        return new GetShipmentRqType();
    }

    /**
     * Create an instance of {@link SaveShipmentRqType }
     * 
     */
    public SaveShipmentRqType createSaveShipmentRqType() {
        return new SaveShipmentRqType();
    }

    /**
     * Create an instance of {@link ShipRqType }
     * 
     */
    public ShipRqType createShipRqType() {
        return new ShipRqType();
    }

    /**
     * Create an instance of {@link CarrierListRqType }
     * 
     */
    public CarrierListRqType createCarrierListRqType() {
        return new CarrierListRqType();
    }

    /**
     * Create an instance of {@link SetSystemPropertyRqType }
     * 
     */
    public SetSystemPropertyRqType createSetSystemPropertyRqType() {
        return new SetSystemPropertyRqType();
    }

    /**
     * Create an instance of {@link GetSystemPropertyRqType }
     * 
     */
    public GetSystemPropertyRqType createGetSystemPropertyRqType() {
        return new GetSystemPropertyRqType();
    }

    /**
     * Create an instance of {@link OpenModuleRqType }
     * 
     */
    public OpenModuleRqType createOpenModuleRqType() {
        return new OpenModuleRqType();
    }

    /**
     * Create an instance of {@link CustomerGetRqType }
     * 
     */
    public CustomerGetRqType createCustomerGetRqType() {
        return new CustomerGetRqType();
    }

    /**
     * Create an instance of {@link GetAccountBalanceRqType }
     * 
     */
    public GetAccountBalanceRqType createGetAccountBalanceRqType() {
        return new GetAccountBalanceRqType();
    }

    /**
     * Create an instance of {@link GetNextNumberRqType }
     * 
     */
    public GetNextNumberRqType createGetNextNumberRqType() {
        return new GetNextNumberRqType();
    }

    /**
     * Create an instance of {@link PartGetRqType }
     * 
     */
    public PartGetRqType createPartGetRqType() {
        return new PartGetRqType();
    }

    /**
     * Create an instance of {@link PartSaveRqType }
     * 
     */
    public PartSaveRqType createPartSaveRqType() {
        return new PartSaveRqType();
    }

    /**
     * Create an instance of {@link ProductGetRqType }
     * 
     */
    public ProductGetRqType createProductGetRqType() {
        return new ProductGetRqType();
    }

    /**
     * Create an instance of {@link ProductSaveRqType }
     * 
     */
    public ProductSaveRqType createProductSaveRqType() {
        return new ProductSaveRqType();
    }

    /**
     * Create an instance of {@link VendorGetRqType }
     * 
     */
    public VendorGetRqType createVendorGetRqType() {
        return new VendorGetRqType();
    }

    /**
     * Create an instance of {@link VendorSaveRqType }
     * 
     */
    public VendorSaveRqType createVendorSaveRqType() {
        return new VendorSaveRqType();
    }

    /**
     * Create an instance of {@link DiscountGetRqType }
     * 
     */
    public DiscountGetRqType createDiscountGetRqType() {
        return new DiscountGetRqType();
    }

    /**
     * Create an instance of {@link CalculateSORqType }
     * 
     */
    public CalculateSORqType createCalculateSORqType() {
        return new CalculateSORqType();
    }

    /**
     * Create an instance of {@link TaxRateGetRqType }
     * 
     */
    public TaxRateGetRqType createTaxRateGetRqType() {
        return new TaxRateGetRqType();
    }

    /**
     * Create an instance of {@link QBClassListGetRqType }
     * 
     */
    public QBClassListGetRqType createQBClassListGetRqType() {
        return new QBClassListGetRqType();
    }

    /**
     * Create an instance of {@link GetTotalInventoryRqType }
     * 
     */
    public GetTotalInventoryRqType createGetTotalInventoryRqType() {
        return new GetTotalInventoryRqType();
    }

    /**
     * Create an instance of {@link HoldPickItemRqType }
     * 
     */
    public HoldPickItemRqType createHoldPickItemRqType() {
        return new HoldPickItemRqType();
    }

    /**
     * Create an instance of {@link MakePaymentRqType }
     * 
     */
    public MakePaymentRqType createMakePaymentRqType() {
        return new MakePaymentRqType();
    }

    /**
     * Create an instance of {@link QuickShipRqType }
     * 
     */
    public QuickShipRqType createQuickShipRqType() {
        return new QuickShipRqType();
    }

    /**
     * Create an instance of {@link SaveDiscountRqType }
     * 
     */
    public SaveDiscountRqType createSaveDiscountRqType() {
        return new SaveDiscountRqType();
    }

    /**
     * Create an instance of {@link SaveReceiptRqType }
     * 
     */
    public SaveReceiptRqType createSaveReceiptRqType() {
        return new SaveReceiptRqType();
    }

    /**
     * Create an instance of {@link GetReceiptRqType }
     * 
     */
    public GetReceiptRqType createGetReceiptRqType() {
        return new GetReceiptRqType();
    }

    /**
     * Create an instance of {@link SaveTaxRateRqType }
     * 
     */
    public SaveTaxRateRqType createSaveTaxRateRqType() {
        return new SaveTaxRateRqType();
    }

    /**
     * Create an instance of {@link GetAccountListRqType }
     * 
     */
    public GetAccountListRqType createGetAccountListRqType() {
        return new GetAccountListRqType();
    }

    /**
     * Create an instance of {@link TransferOrderSaveRqType }
     * 
     */
    public TransferOrderSaveRqType createTransferOrderSaveRqType() {
        return new TransferOrderSaveRqType();
    }

    /**
     * Create an instance of {@link LoadSORqType }
     * 
     */
    public LoadSORqType createLoadSORqType() {
        return new LoadSORqType();
    }

    /**
     * Create an instance of {@link LoadTransferOrderRqType }
     * 
     */
    public LoadTransferOrderRqType createLoadTransferOrderRqType() {
        return new LoadTransferOrderRqType();
    }

    /**
     * Create an instance of {@link GetTransferOrderListRqType }
     * 
     */
    public GetTransferOrderListRqType createGetTransferOrderListRqType() {
        return new GetTransferOrderListRqType();
    }

    /**
     * Create an instance of {@link GetWorkOrderRqType }
     * 
     */
    public GetWorkOrderRqType createGetWorkOrderRqType() {
        return new GetWorkOrderRqType();
    }

    /**
     * Create an instance of {@link SaveWorkOrderRqType }
     * 
     */
    public SaveWorkOrderRqType createSaveWorkOrderRqType() {
        return new SaveWorkOrderRqType();
    }

    /**
     * Create an instance of {@link FbiMsgsRs }
     * 
     */
    public FbiMsgsRs createFbiMsgsRs() {
        return new FbiMsgsRs();
    }

    /**
     * Create an instance of {@link TagQueryRsType }
     * 
     */
    public TagQueryRsType createTagQueryRsType() {
        return new TagQueryRsType();
    }

    /**
     * Create an instance of {@link PartTagQueryRsType }
     * 
     */
    public PartTagQueryRsType createPartTagQueryRsType() {
        return new PartTagQueryRsType();
    }

    /**
     * Create an instance of {@link LocationQueryRsType }
     * 
     */
    public LocationQueryRsType createLocationQueryRsType() {
        return new LocationQueryRsType();
    }

    /**
     * Create an instance of {@link TagMoveRsType }
     * 
     */
    public TagMoveRsType createTagMoveRsType() {
        return new TagMoveRsType();
    }

    /**
     * Create an instance of {@link CustomerListRsType }
     * 
     */
    public CustomerListRsType createCustomerListRsType() {
        return new CustomerListRsType();
    }

    /**
     * Create an instance of {@link CustomerNameListRsType }
     * 
     */
    public CustomerNameListRsType createCustomerNameListRsType() {
        return new CustomerNameListRsType();
    }

    /**
     * Create an instance of {@link CustomerSaveRsType }
     * 
     */
    public CustomerSaveRsType createCustomerSaveRsType() {
        return new CustomerSaveRsType();
    }

    /**
     * Create an instance of {@link VendorListRsType }
     * 
     */
    public VendorListRsType createVendorListRsType() {
        return new VendorListRsType();
    }

    /**
     * Create an instance of {@link VendorNameListRsType }
     * 
     */
    public VendorNameListRsType createVendorNameListRsType() {
        return new VendorNameListRsType();
    }

    /**
     * Create an instance of {@link ImportRsType }
     * 
     */
    public ImportRsType createImportRsType() {
        return new ImportRsType();
    }

    /**
     * Create an instance of {@link ImportListRsType }
     * 
     */
    public ImportListRsType createImportListRsType() {
        return new ImportListRsType();
    }

    /**
     * Create an instance of {@link ExportRsType }
     * 
     */
    public ExportRsType createExportRsType() {
        return new ExportRsType();
    }

    /**
     * Create an instance of {@link ExportListRsType }
     * 
     */
    public ExportListRsType createExportListRsType() {
        return new ExportListRsType();
    }

    /**
     * Create an instance of {@link LoginRsType }
     * 
     */
    public LoginRsType createLoginRsType() {
        return new LoginRsType();
    }

    /**
     * Create an instance of {@link CycleCountQueryRsType }
     * 
     */
    public CycleCountQueryRsType createCycleCountQueryRsType() {
        return new CycleCountQueryRsType();
    }

    /**
     * Create an instance of {@link CycleCountRsType }
     * 
     */
    public CycleCountRsType createCycleCountRsType() {
        return new CycleCountRsType();
    }

    /**
     * Create an instance of {@link PickQueryRsType }
     * 
     */
    public PickQueryRsType createPickQueryRsType() {
        return new PickQueryRsType();
    }

    /**
     * Create an instance of {@link GetPickRsType }
     * 
     */
    public GetPickRsType createGetPickRsType() {
        return new GetPickRsType();
    }

    /**
     * Create an instance of {@link SavePickRsType }
     * 
     */
    public SavePickRsType createSavePickRsType() {
        return new SavePickRsType();
    }

    /**
     * Create an instance of {@link PickRsType }
     * 
     */
    public PickRsType createPickRsType() {
        return new PickRsType();
    }

    /**
     * Create an instance of {@link FinishPickRsType }
     * 
     */
    public FinishPickRsType createFinishPickRsType() {
        return new FinishPickRsType();
    }

    /**
     * Create an instance of {@link TagInfoRsType }
     * 
     */
    public TagInfoRsType createTagInfoRsType() {
        return new TagInfoRsType();
    }

    /**
     * Create an instance of {@link YieldRsType }
     * 
     */
    public YieldRsType createYieldRsType() {
        return new YieldRsType();
    }

    /**
     * Create an instance of {@link PartQueryRsType }
     * 
     */
    public PartQueryRsType createPartQueryRsType() {
        return new PartQueryRsType();
    }

    /**
     * Create an instance of {@link PartCostRsType }
     * 
     */
    public PartCostRsType createPartCostRsType() {
        return new PartCostRsType();
    }

    /**
     * Create an instance of {@link ProductQueryRsType }
     * 
     */
    public ProductQueryRsType createProductQueryRsType() {
        return new ProductQueryRsType();
    }

    /**
     * Create an instance of {@link ReceivingListRsType }
     * 
     */
    public ReceivingListRsType createReceivingListRsType() {
        return new ReceivingListRsType();
    }

    /**
     * Create an instance of {@link ReceivingItemsRsType }
     * 
     */
    public ReceivingItemsRsType createReceivingItemsRsType() {
        return new ReceivingItemsRsType();
    }

    /**
     * Create an instance of {@link ReceiveRsType }
     * 
     */
    public ReceiveRsType createReceiveRsType() {
        return new ReceiveRsType();
    }

    /**
     * Create an instance of {@link AddInventoryRsType }
     * 
     */
    public AddInventoryRsType createAddInventoryRsType() {
        return new AddInventoryRsType();
    }

    /**
     * Create an instance of {@link AdjustInventoryRsType }
     * 
     */
    public AdjustInventoryRsType createAdjustInventoryRsType() {
        return new AdjustInventoryRsType();
    }

    /**
     * Create an instance of {@link UOMRsType }
     * 
     */
    public UOMRsType createUOMRsType() {
        return new UOMRsType();
    }

    /**
     * Create an instance of {@link LocationGroupRsType }
     * 
     */
    public LocationGroupRsType createLocationGroupRsType() {
        return new LocationGroupRsType();
    }

    /**
     * Create an instance of {@link DefPartLocQueryRsType }
     * 
     */
    public DefPartLocQueryRsType createDefPartLocQueryRsType() {
        return new DefPartLocQueryRsType();
    }

    /**
     * Create an instance of {@link SetDefPartLocRsType }
     * 
     */
    public SetDefPartLocRsType createSetDefPartLocRsType() {
        return new SetDefPartLocRsType();
    }

    /**
     * Create an instance of {@link DefLocListRsType }
     * 
     */
    public DefLocListRsType createDefLocListRsType() {
        return new DefLocListRsType();
    }

    /**
     * Create an instance of {@link SavePORsType }
     * 
     */
    public SavePORsType createSavePORsType() {
        return new SavePORsType();
    }

    /**
     * Create an instance of {@link SaveSORsType }
     * 
     */
    public SaveSORsType createSaveSORsType() {
        return new SaveSORsType();
    }

    /**
     * Create an instance of {@link GetPOListRsType }
     * 
     */
    public GetPOListRsType createGetPOListRsType() {
        return new GetPOListRsType();
    }

    /**
     * Create an instance of {@link GetSOListRsType }
     * 
     */
    public GetSOListRsType createGetSOListRsType() {
        return new GetSOListRsType();
    }

    /**
     * Create an instance of {@link GetShipListRsType }
     * 
     */
    public GetShipListRsType createGetShipListRsType() {
        return new GetShipListRsType();
    }

    /**
     * Create an instance of {@link GetShipNowListRsType }
     * 
     */
    public GetShipNowListRsType createGetShipNowListRsType() {
        return new GetShipNowListRsType();
    }

    /**
     * Create an instance of {@link GetShipmentRsType }
     * 
     */
    public GetShipmentRsType createGetShipmentRsType() {
        return new GetShipmentRsType();
    }

    /**
     * Create an instance of {@link SaveShipmentRsType }
     * 
     */
    public SaveShipmentRsType createSaveShipmentRsType() {
        return new SaveShipmentRsType();
    }

    /**
     * Create an instance of {@link ShipRsType }
     * 
     */
    public ShipRsType createShipRsType() {
        return new ShipRsType();
    }

    /**
     * Create an instance of {@link CarrierListRsType }
     * 
     */
    public CarrierListRsType createCarrierListRsType() {
        return new CarrierListRsType();
    }

    /**
     * Create an instance of {@link MessageRsType }
     * 
     */
    public MessageRsType createMessageRsType() {
        return new MessageRsType();
    }

    /**
     * Create an instance of {@link SetSystemPropertyRsType }
     * 
     */
    public SetSystemPropertyRsType createSetSystemPropertyRsType() {
        return new SetSystemPropertyRsType();
    }

    /**
     * Create an instance of {@link GetSystemPropertyRsType }
     * 
     */
    public GetSystemPropertyRsType createGetSystemPropertyRsType() {
        return new GetSystemPropertyRsType();
    }

    /**
     * Create an instance of {@link OpenModuleRsType }
     * 
     */
    public OpenModuleRsType createOpenModuleRsType() {
        return new OpenModuleRsType();
    }

    /**
     * Create an instance of {@link CustomerGetRsType }
     * 
     */
    public CustomerGetRsType createCustomerGetRsType() {
        return new CustomerGetRsType();
    }

    /**
     * Create an instance of {@link GetAccountBalanceRsType }
     * 
     */
    public GetAccountBalanceRsType createGetAccountBalanceRsType() {
        return new GetAccountBalanceRsType();
    }

    /**
     * Create an instance of {@link GetNextNumberRsType }
     * 
     */
    public GetNextNumberRsType createGetNextNumberRsType() {
        return new GetNextNumberRsType();
    }

    /**
     * Create an instance of {@link PartGetRsType }
     * 
     */
    public PartGetRsType createPartGetRsType() {
        return new PartGetRsType();
    }

    /**
     * Create an instance of {@link PartSaveRsType }
     * 
     */
    public PartSaveRsType createPartSaveRsType() {
        return new PartSaveRsType();
    }

    /**
     * Create an instance of {@link ProductSaveRsType }
     * 
     */
    public ProductSaveRsType createProductSaveRsType() {
        return new ProductSaveRsType();
    }

    /**
     * Create an instance of {@link ProductGetRsType }
     * 
     */
    public ProductGetRsType createProductGetRsType() {
        return new ProductGetRsType();
    }

    /**
     * Create an instance of {@link VendorSaveRsType }
     * 
     */
    public VendorSaveRsType createVendorSaveRsType() {
        return new VendorSaveRsType();
    }

    /**
     * Create an instance of {@link VendorGetRsType }
     * 
     */
    public VendorGetRsType createVendorGetRsType() {
        return new VendorGetRsType();
    }

    /**
     * Create an instance of {@link DiscountGetRsType }
     * 
     */
    public DiscountGetRsType createDiscountGetRsType() {
        return new DiscountGetRsType();
    }

    /**
     * Create an instance of {@link CalculateSORsType }
     * 
     */
    public CalculateSORsType createCalculateSORsType() {
        return new CalculateSORsType();
    }

    /**
     * Create an instance of {@link TaxRateGetRsType }
     * 
     */
    public TaxRateGetRsType createTaxRateGetRsType() {
        return new TaxRateGetRsType();
    }

    /**
     * Create an instance of {@link QBClassListGetRsType }
     * 
     */
    public QBClassListGetRsType createQBClassListGetRsType() {
        return new QBClassListGetRsType();
    }

    /**
     * Create an instance of {@link GetTotalInventoryRsType }
     * 
     */
    public GetTotalInventoryRsType createGetTotalInventoryRsType() {
        return new GetTotalInventoryRsType();
    }

    /**
     * Create an instance of {@link HoldPickItemRsType }
     * 
     */
    public HoldPickItemRsType createHoldPickItemRsType() {
        return new HoldPickItemRsType();
    }

    /**
     * Create an instance of {@link MakePaymentRsType }
     * 
     */
    public MakePaymentRsType createMakePaymentRsType() {
        return new MakePaymentRsType();
    }

    /**
     * Create an instance of {@link QuickShipRsType }
     * 
     */
    public QuickShipRsType createQuickShipRsType() {
        return new QuickShipRsType();
    }

    /**
     * Create an instance of {@link SaveDiscountRsType }
     * 
     */
    public SaveDiscountRsType createSaveDiscountRsType() {
        return new SaveDiscountRsType();
    }

    /**
     * Create an instance of {@link SaveReceiptRsType }
     * 
     */
    public SaveReceiptRsType createSaveReceiptRsType() {
        return new SaveReceiptRsType();
    }

    /**
     * Create an instance of {@link GetReceiptRsType }
     * 
     */
    public GetReceiptRsType createGetReceiptRsType() {
        return new GetReceiptRsType();
    }

    /**
     * Create an instance of {@link SaveTaxRateRsType }
     * 
     */
    public SaveTaxRateRsType createSaveTaxRateRsType() {
        return new SaveTaxRateRsType();
    }

    /**
     * Create an instance of {@link GetAccountListRsType }
     * 
     */
    public GetAccountListRsType createGetAccountListRsType() {
        return new GetAccountListRsType();
    }

    /**
     * Create an instance of {@link TransferOrderSaveRsType }
     * 
     */
    public TransferOrderSaveRsType createTransferOrderSaveRsType() {
        return new TransferOrderSaveRsType();
    }

    /**
     * Create an instance of {@link LoadTransferOrderRsType }
     * 
     */
    public LoadTransferOrderRsType createLoadTransferOrderRsType() {
        return new LoadTransferOrderRsType();
    }

    /**
     * Create an instance of {@link GetTransferOrderListRsType }
     * 
     */
    public GetTransferOrderListRsType createGetTransferOrderListRsType() {
        return new GetTransferOrderListRsType();
    }

    /**
     * Create an instance of {@link LoadSORsType }
     * 
     */
    public LoadSORsType createLoadSORsType() {
        return new LoadSORsType();
    }

    /**
     * Create an instance of {@link GetWorkOrderRsType }
     * 
     */
    public GetWorkOrderRsType createGetWorkOrderRsType() {
        return new GetWorkOrderRsType();
    }

    /**
     * Create an instance of {@link SaveWorkOrderRsType }
     * 
     */
    public SaveWorkOrderRsType createSaveWorkOrderRsType() {
        return new SaveWorkOrderRsType();
    }

    /**
     * Create an instance of {@link ShipSearchItem }
     * 
     */
    public ShipSearchItem createShipSearchItem() {
        return new ShipSearchItem();
    }

    /**
     * Create an instance of {@link ReceiveTicket }
     * 
     */
    public ReceiveTicket createReceiveTicket() {
        return new ReceiveTicket();
    }

    /**
     * Create an instance of {@link Shipping }
     * 
     */
    public Shipping createShipping() {
        return new Shipping();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link Cartons }
     * 
     */
    public Cartons createCartons() {
        return new Cartons();
    }

    /**
     * Create an instance of {@link Carton }
     * 
     */
    public Carton createCarton() {
        return new Carton();
    }

    /**
     * Create an instance of {@link ShippingItems }
     * 
     */
    public ShippingItems createShippingItems() {
        return new ShippingItems();
    }

    /**
     * Create an instance of {@link ShippingItem }
     * 
     */
    public ShippingItem createShippingItem() {
        return new ShippingItem();
    }

    /**
     * Create an instance of {@link UOM }
     * 
     */
    public UOM createUOM() {
        return new UOM();
    }

    /**
     * Create an instance of {@link UOMConversions }
     * 
     */
    public UOMConversions createUOMConversions() {
        return new UOMConversions();
    }

    /**
     * Create an instance of {@link UOMConversion }
     * 
     */
    public UOMConversion createUOMConversion() {
        return new UOMConversion();
    }

    /**
     * Create an instance of {@link WeightUOM }
     * 
     */
    public WeightUOM createWeightUOM() {
        return new WeightUOM();
    }

    /**
     * Create an instance of {@link Tracking }
     * 
     */
    public Tracking createTracking() {
        return new Tracking();
    }

    /**
     * Create an instance of {@link TrackingItem }
     * 
     */
    public TrackingItem createTrackingItem() {
        return new TrackingItem();
    }

    /**
     * Create an instance of {@link SerialBoxList }
     * 
     */
    public SerialBoxList createSerialBoxList() {
        return new SerialBoxList();
    }

    /**
     * Create an instance of {@link RMAItems }
     * 
     */
    public RMAItems createRMAItems() {
        return new RMAItems();
    }

    /**
     * Create an instance of {@link RMAItem }
     * 
     */
    public RMAItem createRMAItem() {
        return new RMAItem();
    }

    /**
     * Create an instance of {@link PurchaseOrderItem }
     * 
     */
    public PurchaseOrderItem createPurchaseOrderItem() {
        return new PurchaseOrderItem();
    }

    /**
     * Create an instance of {@link KitItem }
     * 
     */
    public KitItem createKitItem() {
        return new KitItem();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link CustomFields }
     * 
     */
    public CustomFields createCustomFields() {
        return new CustomFields();
    }

    /**
     * Create an instance of {@link CustomField }
     * 
     */
    public CustomField createCustomField() {
        return new CustomField();
    }

    /**
     * Create an instance of {@link CustomList }
     * 
     */
    public CustomList createCustomList() {
        return new CustomList();
    }

    /**
     * Create an instance of {@link Part.PartTrackingList }
     * 
     */
    public Part.PartTrackingList createPartPartTrackingList() {
        return new Part.PartTrackingList();
    }

    /**
     * Create an instance of {@link VendorPartNums }
     * 
     */
    public VendorPartNums createVendorPartNums() {
        return new VendorPartNums();
    }

    /**
     * Create an instance of {@link TaxRate }
     * 
     */
    public TaxRate createTaxRate() {
        return new TaxRate();
    }

    /**
     * Create an instance of {@link Discount }
     * 
     */
    public Discount createDiscount() {
        return new Discount();
    }

    /**
     * Create an instance of {@link KitOption }
     * 
     */
    public KitOption createKitOption() {
        return new KitOption();
    }

    /**
     * Create an instance of {@link ReceivedReceipt }
     * 
     */
    public ReceivedReceipt createReceivedReceipt() {
        return new ReceivedReceipt();
    }

    /**
     * Create an instance of {@link PartTracks }
     * 
     */
    public PartTracks createPartTracks() {
        return new PartTracks();
    }

    /**
     * Create an instance of {@link PartDefaultLocation }
     * 
     */
    public PartDefaultLocation createPartDefaultLocation() {
        return new PartDefaultLocation();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link PurchaseOrder }
     * 
     */
    public PurchaseOrder createPurchaseOrder() {
        return new PurchaseOrder();
    }

    /**
     * Create an instance of {@link RemitType }
     * 
     */
    public RemitType createRemitType() {
        return new RemitType();
    }

    /**
     * Create an instance of {@link ShipType }
     * 
     */
    public ShipType createShipType() {
        return new ShipType();
    }

    /**
     * Create an instance of {@link SalesOrder }
     * 
     */
    public SalesOrder createSalesOrder() {
        return new SalesOrder();
    }

    /**
     * Create an instance of {@link BillType }
     * 
     */
    public BillType createBillType() {
        return new BillType();
    }

    /**
     * Create an instance of {@link Memos }
     * 
     */
    public Memos createMemos() {
        return new Memos();
    }

    /**
     * Create an instance of {@link Memo }
     * 
     */
    public Memo createMemo() {
        return new Memo();
    }

    /**
     * Create an instance of {@link Items }
     * 
     */
    public Items createItems() {
        return new Items();
    }

    /**
     * Create an instance of {@link WOItems }
     * 
     */
    public WOItems createWOItems() {
        return new WOItems();
    }

    /**
     * Create an instance of {@link WOItem.DestLocation }
     * 
     */
    public WOItem.DestLocation createWOItemDestLocation() {
        return new WOItem.DestLocation();
    }

    /**
     * Create an instance of {@link Carriers }
     * 
     */
    public Carriers createCarriers() {
        return new Carriers();
    }

    /**
     * Create an instance of {@link PickItem }
     * 
     */
    public PickItem createPickItem() {
        return new PickItem();
    }

    /**
     * Create an instance of {@link Tag }
     * 
     */
    public Tag createTag() {
        return new Tag();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link SourceLocation }
     * 
     */
    public SourceLocation createSourceLocation() {
        return new SourceLocation();
    }

    /**
     * Create an instance of {@link TransferOrderItems }
     * 
     */
    public TransferOrderItems createTransferOrderItems() {
        return new TransferOrderItems();
    }

    /**
     * Create an instance of {@link TransferOrderItem }
     * 
     */
    public TransferOrderItem createTransferOrderItem() {
        return new TransferOrderItem();
    }

    /**
     * Create an instance of {@link PickSearchItem }
     * 
     */
    public PickSearchItem createPickSearchItem() {
        return new PickSearchItem();
    }

    /**
     * Create an instance of {@link AvailablePickLocations }
     * 
     */
    public AvailablePickLocations createAvailablePickLocations() {
        return new AvailablePickLocations();
    }

    /**
     * Create an instance of {@link PickOrders }
     * 
     */
    public PickOrders createPickOrders() {
        return new PickOrders();
    }

    /**
     * Create an instance of {@link PickOrder }
     * 
     */
    public PickOrder createPickOrder() {
        return new PickOrder();
    }

    /**
     * Create an instance of {@link Contacts }
     * 
     */
    public Contacts createContacts() {
        return new Contacts();
    }

    /**
     * Create an instance of {@link ContactInformation }
     * 
     */
    public ContactInformation createContactInformation() {
        return new ContactInformation();
    }

    /**
     * Create an instance of {@link Receipt }
     * 
     */
    public Receipt createReceipt() {
        return new Receipt();
    }

    /**
     * Create an instance of {@link ReceiptItems }
     * 
     */
    public ReceiptItems createReceiptItems() {
        return new ReceiptItems();
    }

    /**
     * Create an instance of {@link ReceiveItem }
     * 
     */
    public ReceiveItem createReceiveItem() {
        return new ReceiveItem();
    }

    /**
     * Create an instance of {@link ReceivedReceipts }
     * 
     */
    public ReceivedReceipts createReceivedReceipts() {
        return new ReceivedReceipts();
    }

    /**
     * Create an instance of {@link LocationGroup }
     * 
     */
    public LocationGroup createLocationGroup() {
        return new LocationGroup();
    }

    /**
     * Create an instance of {@link WO.User }
     * 
     */
    public WO.User createWOUser() {
        return new WO.User();
    }

    /**
     * Create an instance of {@link AddressInformation }
     * 
     */
    public AddressInformation createAddressInformation() {
        return new AddressInformation();
    }

    /**
     * Create an instance of {@link Carrier }
     * 
     */
    public Carrier createCarrier() {
        return new Carrier();
    }

    /**
     * Create an instance of {@link OrderHistorys }
     * 
     */
    public OrderHistorys createOrderHistorys() {
        return new OrderHistorys();
    }

    /**
     * Create an instance of {@link OrderHistory }
     * 
     */
    public OrderHistory createOrderHistory() {
        return new OrderHistory();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link AddressInformationList }
     * 
     */
    public AddressInformationList createAddressInformationList() {
        return new AddressInformationList();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link OrderNums }
     * 
     */
    public OrderNums createOrderNums() {
        return new OrderNums();
    }

    /**
     * Create an instance of {@link Receive }
     * 
     */
    public Receive createReceive() {
        return new Receive();
    }

    /**
     * Create an instance of {@link Pick }
     * 
     */
    public Pick createPick() {
        return new Pick();
    }

    /**
     * Create an instance of {@link PickItems }
     * 
     */
    public PickItems createPickItems() {
        return new PickItems();
    }

    /**
     * Create an instance of {@link Exports }
     * 
     */
    public Exports createExports() {
        return new Exports();
    }

    /**
     * Create an instance of {@link TrackingType }
     * 
     */
    public TrackingType createTrackingType() {
        return new TrackingType();
    }

    /**
     * Create an instance of {@link AssociatedProduct }
     * 
     */
    public AssociatedProduct createAssociatedProduct() {
        return new AssociatedProduct();
    }

    /**
     * Create an instance of {@link Tracks }
     * 
     */
    public Tracks createTracks() {
        return new Tracks();
    }

    /**
     * Create an instance of {@link ModuleAccess }
     * 
     */
    public ModuleAccess createModuleAccess() {
        return new ModuleAccess();
    }

    /**
     * Create an instance of {@link PartUOM }
     * 
     */
    public PartUOM createPartUOM() {
        return new PartUOM();
    }

    /**
     * Create an instance of {@link TransferOrder }
     * 
     */
    public TransferOrder createTransferOrder() {
        return new TransferOrder();
    }

    /**
     * Create an instance of {@link ShipFromLGType }
     * 
     */
    public ShipFromLGType createShipFromLGType() {
        return new ShipFromLGType();
    }

    /**
     * Create an instance of {@link ShipFromAddressType }
     * 
     */
    public ShipFromAddressType createShipFromAddressType() {
        return new ShipFromAddressType();
    }

    /**
     * Create an instance of {@link ShipToLGType }
     * 
     */
    public ShipToLGType createShipToLGType() {
        return new ShipToLGType();
    }

    /**
     * Create an instance of {@link ShipToAddressType }
     * 
     */
    public ShipToAddressType createShipToAddressType() {
        return new ShipToAddressType();
    }

    /**
     * Create an instance of {@link MainLocationTagType }
     * 
     */
    public MainLocationTagType createMainLocationTagType() {
        return new MainLocationTagType();
    }

    /**
     * Create an instance of {@link Addresses }
     * 
     */
    public Addresses createAddresses() {
        return new Addresses();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link WorkOrderSearch }
     * 
     */
    public WorkOrderSearch createWorkOrderSearch() {
        return new WorkOrderSearch();
    }

    /**
     * Create an instance of {@link Salesman }
     * 
     */
    public Salesman createSalesman() {
        return new Salesman();
    }

    /**
     * Create an instance of {@link TrackingTypeList }
     * 
     */
    public TrackingTypeList createTrackingTypeList() {
        return new TrackingTypeList();
    }

    /**
     * Create an instance of {@link Groups }
     * 
     */
    public Groups createGroups() {
        return new Groups();
    }

    /**
     * Create an instance of {@link RMA }
     * 
     */
    public RMA createRMA() {
        return new RMA();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link ShippingIDs }
     * 
     */
    public ShippingIDs createShippingIDs() {
        return new ShippingIDs();
    }

    /**
     * Create an instance of {@link Clients }
     * 
     */
    public Clients createClients() {
        return new Clients();
    }

    /**
     * Create an instance of {@link Vendor }
     * 
     */
    public Vendor createVendor() {
        return new Vendor();
    }

    /**
     * Create an instance of {@link DestinationType }
     * 
     */
    public DestinationType createDestinationType() {
        return new DestinationType();
    }

    /**
     * Create an instance of {@link LoadPORqType }
     * 
     */
    public LoadPORqType createLoadPORqType() {
        return new LoadPORqType();
    }

    /**
     * Create an instance of {@link LoadPORsType }
     * 
     */
    public LoadPORsType createLoadPORsType() {
        return new LoadPORsType();
    }

    /**
     * Create an instance of {@link DestinationTagType }
     * 
     */
    public DestinationTagType createDestinationTagType() {
        return new DestinationTagType();
    }

    /**
     * Create an instance of {@link PickOrdersType2 }
     * 
     */
    public PickOrdersType2 createPickOrdersType2() {
        return new PickOrdersType2();
    }

    /**
     * Create an instance of {@link LocationGroupType }
     * 
     */
    public LocationGroupType createLocationGroupType() {
        return new LocationGroupType();
    }

    /**
     * Create an instance of {@link CycleCountOrdersType }
     * 
     */
    public CycleCountOrdersType createCycleCountOrdersType() {
        return new CycleCountOrdersType();
    }

    /**
     * Create an instance of {@link StateType }
     * 
     */
    public StateType createStateType() {
        return new StateType();
    }

    /**
     * Create an instance of {@link DefaultLocationType }
     * 
     */
    public DefaultLocationType createDefaultLocationType() {
        return new DefaultLocationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "PriorityID")
    public JAXBElement<BigInteger> createPriorityID(BigInteger value) {
        return new JAXBElement<BigInteger>(_PriorityID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "VendorID")
    public JAXBElement<BigInteger> createVendorID(BigInteger value) {
        return new JAXBElement<BigInteger>(_VendorID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "DateLastModified")
    public JAXBElement<String> createDateLastModified(String value) {
        return new JAXBElement<String>(_DateLastModified_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "PartID")
    public JAXBElement<BigInteger> createPartID(BigInteger value) {
        return new JAXBElement<BigInteger>(_PartID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "SortID")
    public JAXBElement<BigInteger> createSortID(BigInteger value) {
        return new JAXBElement<BigInteger>(_SortID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "IsActive")
    public JAXBElement<Boolean> createIsActive(Boolean value) {
        return new JAXBElement<Boolean>(_IsActive_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "ProductNum")
    public JAXBElement<String> createProductNum(String value) {
        return new JAXBElement<String>(_ProductNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "QuantityToFulfill")
    public JAXBElement<String> createQuantityToFulfill(String value) {
        return new JAXBElement<String>(_QuantityToFulfill_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Rev")
    public JAXBElement<String> createRev(String value) {
        return new JAXBElement<String>(_Rev_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "UPC")
    public JAXBElement<String> createUPC(String value) {
        return new JAXBElement<String>(_UPC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "TimeModified")
    public JAXBElement<String> createTimeModified(String value) {
        return new JAXBElement<String>(_TimeModified_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "LotNum")
    public JAXBElement<String> createLotNum(String value) {
        return new JAXBElement<String>(_LotNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Barcode")
    public JAXBElement<String> createBarcode(String value) {
        return new JAXBElement<String>(_Barcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "CogsAccountID")
    public JAXBElement<BigInteger> createCogsAccountID(BigInteger value) {
        return new JAXBElement<BigInteger>(_CogsAccountID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "DateFinished")
    public JAXBElement<String> createDateFinished(String value) {
        return new JAXBElement<String>(_DateFinished_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "QBClassID")
    public JAXBElement<BigInteger> createQBClassID(BigInteger value) {
        return new JAXBElement<BigInteger>(_QBClassID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "StatusID")
    public JAXBElement<BigInteger> createStatusID(BigInteger value) {
        return new JAXBElement<BigInteger>(_StatusID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "DefPaymentTermsID")
    public JAXBElement<BigInteger> createDefPaymentTermsID(BigInteger value) {
        return new JAXBElement<BigInteger>(_DefPaymentTermsID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "MOItemID")
    public JAXBElement<BigInteger> createMOItemID(BigInteger value) {
        return new JAXBElement<BigInteger>(_MOItemID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "CustomerID")
    public JAXBElement<BigInteger> createCustomerID(BigInteger value) {
        return new JAXBElement<BigInteger>(_CustomerID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "QtyScrapped")
    public JAXBElement<String> createQtyScrapped(String value) {
        return new JAXBElement<String>(_QtyScrapped_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "DefShipTermsID")
    public JAXBElement<BigInteger> createDefShipTermsID(BigInteger value) {
        return new JAXBElement<BigInteger>(_DefShipTermsID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "DateStarted")
    public JAXBElement<String> createDateStarted(String value) {
        return new JAXBElement<String>(_DateStarted_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "PartNum")
    public JAXBElement<String> createPartNum(String value) {
        return new JAXBElement<String>(_PartNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Number")
    public JAXBElement<String> createNumber(String value) {
        return new JAXBElement<String>(_Number_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "AccountID")
    public JAXBElement<BigInteger> createAccountID(BigInteger value) {
        return new JAXBElement<BigInteger>(_AccountID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "AccountingHash")
    public JAXBElement<String> createAccountingHash(String value) {
        return new JAXBElement<String>(_AccountingHash_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Num")
    public JAXBElement<BigInteger> createNum(BigInteger value) {
        return new JAXBElement<BigInteger>(_Num_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "AccountingID")
    public JAXBElement<String> createAccountingID(String value) {
        return new JAXBElement<String>(_AccountingID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "DateCreated")
    public JAXBElement<String> createDateCreated(String value) {
        return new JAXBElement<String>(_DateCreated_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "PartClassID")
    public JAXBElement<BigInteger> createPartClassID(BigInteger value) {
        return new JAXBElement<BigInteger>(_PartClassID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Manufacturer")
    public JAXBElement<String> createManufacturer(String value) {
        return new JAXBElement<String>(_Manufacturer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "LastChangedUser")
    public JAXBElement<String> createLastChangedUser(String value) {
        return new JAXBElement<String>(_LastChangedUser_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "LocationID")
    public JAXBElement<BigInteger> createLocationID(BigInteger value) {
        return new JAXBElement<BigInteger>(_LocationID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "TagNum")
    public JAXBElement<BigInteger> createTagNum(BigInteger value) {
        return new JAXBElement<BigInteger>(_TagNum_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "QuantityFulfilled")
    public JAXBElement<String> createQuantityFulfilled(String value) {
        return new JAXBElement<String>(_QuantityFulfilled_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "CarrierID")
    public JAXBElement<BigInteger> createCarrierID(BigInteger value) {
        return new JAXBElement<BigInteger>(_CarrierID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "TaxRateID")
    public JAXBElement<BigInteger> createTaxRateID(BigInteger value) {
        return new JAXBElement<BigInteger>(_TaxRateID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "UserName")
    public JAXBElement<String> createUserName(String value) {
        return new JAXBElement<String>(_UserName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "TagID")
    public JAXBElement<BigInteger> createTagID(BigInteger value) {
        return new JAXBElement<BigInteger>(_TagID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "TypeID")
    public JAXBElement<BigInteger> createTypeID(BigInteger value) {
        return new JAXBElement<BigInteger>(_TypeID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "WOID")
    public JAXBElement<BigInteger> createWOID(BigInteger value) {
        return new JAXBElement<BigInteger>(_WOID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "QuantityPicked")
    public JAXBElement<String> createQuantityPicked(String value) {
        return new JAXBElement<String>(_QuantityPicked_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "DateScheduledToStart")
    public JAXBElement<String> createDateScheduledToStart(String value) {
        return new JAXBElement<String>(_DateScheduledToStart_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Info")
    public JAXBElement<String> createInfo(String value) {
        return new JAXBElement<String>(_Info_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "ABCCode")
    public JAXBElement<String> createABCCode(String value) {
        return new JAXBElement<String>(_ABCCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "LocationGroupID")
    public JAXBElement<BigInteger> createLocationGroupID(BigInteger value) {
        return new JAXBElement<BigInteger>(_LocationGroupID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "EditSequence")
    public JAXBElement<String> createEditSequence(String value) {
        return new JAXBElement<String>(_EditSequence_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "DateLastIssued")
    public JAXBElement<String> createDateLastIssued(String value) {
        return new JAXBElement<String>(_DateLastIssued_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "ShippingCost")
    public JAXBElement<String> createShippingCost(String value) {
        return new JAXBElement<String>(_ShippingCost_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Quantity")
    public JAXBElement<String> createQuantity(String value) {
        return new JAXBElement<String>(_Quantity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "DateFirstShipped")
    public JAXBElement<String> createDateFirstShipped(String value) {
        return new JAXBElement<String>(_DateFirstShipped_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "QtyToFulfill")
    public JAXBElement<String> createQtyToFulfill(String value) {
        return new JAXBElement<String>(_QtyToFulfill_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "DateConfirmed")
    public JAXBElement<String> createDateConfirmed(String value) {
        return new JAXBElement<String>(_DateConfirmed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "DateScheduled")
    public JAXBElement<String> createDateScheduled(String value) {
        return new JAXBElement<String>(_DateScheduled_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "QtyUsed")
    public JAXBElement<String> createQtyUsed(String value) {
        return new JAXBElement<String>(_QtyUsed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Note")
    public JAXBElement<String> createNote(String value) {
        return new JAXBElement<String>(_Note_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "Priority")
    public JAXBElement<String> createPriority(String value) {
        return new JAXBElement<String>(_Priority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "FishbowlSDK", name = "ParentID")
    public JAXBElement<BigInteger> createParentID(BigInteger value) {
        return new JAXBElement<BigInteger>(_ParentID_QNAME, BigInteger.class, null, value);
    }

}
