//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{FishbowlSDK}PartID"/>
 *         &lt;element name="PartClassID" type="{FishbowlSDK}DB_ID"/>
 *         &lt;element ref="{FishbowlSDK}TypeID" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}UOM" minOccurs="0"/>
 *         &lt;element name="Num" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element ref="{FishbowlSDK}Description" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}Manufacturer" minOccurs="0"/>
 *         &lt;element name="Details" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element ref="{FishbowlSDK}ABCCode" minOccurs="0"/>
 *         &lt;element name="TagLabel" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="StandardCost" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="HasBOM" type="{FishbowlSDK}BOOLTYPE"/>
 *         &lt;element name="Configurable" type="{FishbowlSDK}BOOLTYPE"/>
 *         &lt;element name="ActiveFlag" type="{FishbowlSDK}BOOLTYPE"/>
 *         &lt;element name="SerializedFlag" type="{FishbowlSDK}BOOLTYPE"/>
 *         &lt;element name="TrackingFlag" type="{FishbowlSDK}BOOLTYPE"/>
 *         &lt;element name="UsedFlag" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="Weight" type="{FishbowlSDK}QUANTYPE" minOccurs="0"/>
 *         &lt;element name="WeightUOMID" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="Width" type="{FishbowlSDK}QUANTYPE" minOccurs="0"/>
 *         &lt;element name="Height" type="{FishbowlSDK}QUANTYPE" minOccurs="0"/>
 *         &lt;element name="Len" type="{FishbowlSDK}QUANTYPE" minOccurs="0"/>
 *         &lt;element name="SizeUOMID" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}UPC"/>
 *         &lt;element ref="{FishbowlSDK}CustomFields" minOccurs="0"/>
 *         &lt;element name="PartTrackingList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{FishbowlSDK}PartTracking" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{FishbowlSDK}VendorPartNums" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "partID",
    "partClassID",
    "typeID",
    "uom",
    "num",
    "description",
    "manufacturer",
    "details",
    "abcCode",
    "tagLabel",
    "standardCost",
    "hasBOM",
    "configurable",
    "activeFlag",
    "serializedFlag",
    "trackingFlag",
    "usedFlag",
    "weight",
    "weightUOMID",
    "width",
    "height",
    "len",
    "sizeUOMID",
    "upc",
    "customFields",
    "partTrackingList",
    "vendorPartNums"
})
@XmlRootElement(name = "Part")
public class Part {

    @XmlElement(name = "PartID", required = true)
    protected BigInteger partID;
    @XmlElement(name = "PartClassID", required = true)
    protected BigInteger partClassID;
    @XmlElement(name = "TypeID")
    protected BigInteger typeID;
    @XmlElement(name = "UOM")
    protected UOM uom;
    @XmlElement(name = "Num", required = true)
    protected String num;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Manufacturer")
    protected String manufacturer;
    @XmlElement(name = "Details", required = true)
    protected String details;
    @XmlElement(name = "ABCCode")
    protected String abcCode;
    @XmlElement(name = "TagLabel")
    protected String tagLabel;
    @XmlElement(name = "StandardCost")
    protected String standardCost;
    @XmlElement(name = "HasBOM", defaultValue = "false")
    protected boolean hasBOM;
    @XmlElement(name = "Configurable", defaultValue = "false")
    protected boolean configurable;
    @XmlElement(name = "ActiveFlag", defaultValue = "true")
    protected boolean activeFlag;
    @XmlElement(name = "SerializedFlag", defaultValue = "true")
    protected boolean serializedFlag;
    @XmlElement(name = "TrackingFlag", defaultValue = "false")
    protected boolean trackingFlag;
    @XmlElement(name = "UsedFlag", defaultValue = "false")
    protected Boolean usedFlag;
    @XmlElement(name = "Weight")
    protected String weight;
    @XmlElement(name = "WeightUOMID")
    protected BigInteger weightUOMID;
    @XmlElement(name = "Width")
    protected String width;
    @XmlElement(name = "Height")
    protected String height;
    @XmlElement(name = "Len")
    protected String len;
    @XmlElement(name = "SizeUOMID")
    protected BigInteger sizeUOMID;
    @XmlElement(name = "UPC", required = true)
    protected String upc;
    @XmlElement(name = "CustomFields")
    protected CustomFields customFields;
    @XmlElement(name = "PartTrackingList")
    protected Part.PartTrackingList partTrackingList;
    @XmlElement(name = "VendorPartNums")
    protected VendorPartNums vendorPartNums;

    /**
     * Gets the value of the partID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPartID() {
        return partID;
    }

    /**
     * Sets the value of the partID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPartID(BigInteger value) {
        this.partID = value;
    }

    /**
     * Gets the value of the partClassID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPartClassID() {
        return partClassID;
    }

    /**
     * Sets the value of the partClassID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPartClassID(BigInteger value) {
        this.partClassID = value;
    }

    /**
     * Gets the value of the typeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTypeID() {
        return typeID;
    }

    /**
     * Sets the value of the typeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTypeID(BigInteger value) {
        this.typeID = value;
    }

    /**
     * Gets the value of the uom property.
     * 
     * @return
     *     possible object is
     *     {@link UOM }
     *     
     */
    public UOM getUOM() {
        return uom;
    }

    /**
     * Sets the value of the uom property.
     * 
     * @param value
     *     allowed object is
     *     {@link UOM }
     *     
     */
    public void setUOM(UOM value) {
        this.uom = value;
    }

    /**
     * Gets the value of the num property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNum() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNum(String value) {
        this.num = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetails(String value) {
        this.details = value;
    }

    /**
     * Gets the value of the abcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getABCCode() {
        return abcCode;
    }

    /**
     * Sets the value of the abcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setABCCode(String value) {
        this.abcCode = value;
    }

    /**
     * Gets the value of the tagLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTagLabel() {
        return tagLabel;
    }

    /**
     * Sets the value of the tagLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTagLabel(String value) {
        this.tagLabel = value;
    }

    /**
     * Gets the value of the standardCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardCost() {
        return standardCost;
    }

    /**
     * Sets the value of the standardCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardCost(String value) {
        this.standardCost = value;
    }

    /**
     * Gets the value of the hasBOM property.
     * 
     */
    public boolean isHasBOM() {
        return hasBOM;
    }

    /**
     * Sets the value of the hasBOM property.
     * 
     */
    public void setHasBOM(boolean value) {
        this.hasBOM = value;
    }

    /**
     * Gets the value of the configurable property.
     * 
     */
    public boolean isConfigurable() {
        return configurable;
    }

    /**
     * Sets the value of the configurable property.
     * 
     */
    public void setConfigurable(boolean value) {
        this.configurable = value;
    }

    /**
     * Gets the value of the activeFlag property.
     * 
     */
    public boolean isActiveFlag() {
        return activeFlag;
    }

    /**
     * Sets the value of the activeFlag property.
     * 
     */
    public void setActiveFlag(boolean value) {
        this.activeFlag = value;
    }

    /**
     * Gets the value of the serializedFlag property.
     * 
     */
    public boolean isSerializedFlag() {
        return serializedFlag;
    }

    /**
     * Sets the value of the serializedFlag property.
     * 
     */
    public void setSerializedFlag(boolean value) {
        this.serializedFlag = value;
    }

    /**
     * Gets the value of the trackingFlag property.
     * 
     */
    public boolean isTrackingFlag() {
        return trackingFlag;
    }

    /**
     * Sets the value of the trackingFlag property.
     * 
     */
    public void setTrackingFlag(boolean value) {
        this.trackingFlag = value;
    }

    /**
     * Gets the value of the usedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsedFlag() {
        return usedFlag;
    }

    /**
     * Sets the value of the usedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsedFlag(Boolean value) {
        this.usedFlag = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeight(String value) {
        this.weight = value;
    }

    /**
     * Gets the value of the weightUOMID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWeightUOMID() {
        return weightUOMID;
    }

    /**
     * Sets the value of the weightUOMID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWeightUOMID(BigInteger value) {
        this.weightUOMID = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the len property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLen() {
        return len;
    }

    /**
     * Sets the value of the len property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLen(String value) {
        this.len = value;
    }

    /**
     * Gets the value of the sizeUOMID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSizeUOMID() {
        return sizeUOMID;
    }

    /**
     * Sets the value of the sizeUOMID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSizeUOMID(BigInteger value) {
        this.sizeUOMID = value;
    }

    /**
     * Gets the value of the upc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPC() {
        return upc;
    }

    /**
     * Sets the value of the upc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPC(String value) {
        this.upc = value;
    }

    /**
     * Gets the value of the customFields property.
     * 
     * @return
     *     possible object is
     *     {@link CustomFields }
     *     
     */
    public CustomFields getCustomFields() {
        return customFields;
    }

    /**
     * Sets the value of the customFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomFields }
     *     
     */
    public void setCustomFields(CustomFields value) {
        this.customFields = value;
    }

    /**
     * Gets the value of the partTrackingList property.
     * 
     * @return
     *     possible object is
     *     {@link Part.PartTrackingList }
     *     
     */
    public Part.PartTrackingList getPartTrackingList() {
        return partTrackingList;
    }

    /**
     * Sets the value of the partTrackingList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Part.PartTrackingList }
     *     
     */
    public void setPartTrackingList(Part.PartTrackingList value) {
        this.partTrackingList = value;
    }

    /**
     * Gets the value of the vendorPartNums property.
     * 
     * @return
     *     possible object is
     *     {@link VendorPartNums }
     *     
     */
    public VendorPartNums getVendorPartNums() {
        return vendorPartNums;
    }

    /**
     * Sets the value of the vendorPartNums property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorPartNums }
     *     
     */
    public void setVendorPartNums(VendorPartNums value) {
        this.vendorPartNums = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{FishbowlSDK}PartTracking" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partTracking"
    })
    public static class PartTrackingList {

        @XmlElement(name = "PartTracking")
        protected List<PartTracking> partTracking;

        /**
         * Gets the value of the partTracking property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the partTracking property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPartTracking().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PartTracking }
         * 
         * 
         */
        public List<PartTracking> getPartTracking() {
            if (partTracking == null) {
                partTracking = new ArrayList<PartTracking>();
            }
            return this.partTracking;
        }

    }

}
