//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PickQueryRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PickQueryRqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StartIndex" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="RecordCount" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="PickNum" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="OrderNum" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="PickType" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Status" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Priority" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="StartDate" type="{FishbowlSDK}DATETYPE" minOccurs="0"/>
 *         &lt;element name="EndDate" type="{FishbowlSDK}DATETYPE" minOccurs="0"/>
 *         &lt;element name="Fulfillable" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="LocationGroup" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PickQueryRqType", propOrder = {
    "startIndex",
    "recordCount",
    "pickNum",
    "orderNum",
    "pickType",
    "status",
    "priority",
    "startDate",
    "endDate",
    "fulfillable",
    "locationGroup"
})
public class PickQueryRqType {

    @XmlElement(name = "StartIndex")
    protected BigInteger startIndex;
    @XmlElement(name = "RecordCount")
    protected BigInteger recordCount;
    @XmlElement(name = "PickNum")
    protected String pickNum;
    @XmlElement(name = "OrderNum")
    protected String orderNum;
    @XmlElement(name = "PickType")
    protected String pickType;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "Priority")
    protected String priority;
    @XmlElement(name = "StartDate")
    protected String startDate;
    @XmlElement(name = "EndDate")
    protected String endDate;
    @XmlElement(name = "Fulfillable")
    protected Boolean fulfillable;
    @XmlElement(name = "LocationGroup")
    protected String locationGroup;

    /**
     * Gets the value of the startIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStartIndex() {
        return startIndex;
    }

    /**
     * Sets the value of the startIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStartIndex(BigInteger value) {
        this.startIndex = value;
    }

    /**
     * Gets the value of the recordCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecordCount() {
        return recordCount;
    }

    /**
     * Sets the value of the recordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecordCount(BigInteger value) {
        this.recordCount = value;
    }

    /**
     * Gets the value of the pickNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickNum() {
        return pickNum;
    }

    /**
     * Sets the value of the pickNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickNum(String value) {
        this.pickNum = value;
    }

    /**
     * Gets the value of the orderNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * Sets the value of the orderNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNum(String value) {
        this.orderNum = value;
    }

    /**
     * Gets the value of the pickType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickType() {
        return pickType;
    }

    /**
     * Sets the value of the pickType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickType(String value) {
        this.pickType = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDate(String value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the fulfillable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFulfillable() {
        return fulfillable;
    }

    /**
     * Sets the value of the fulfillable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFulfillable(Boolean value) {
        this.fulfillable = value;
    }

    /**
     * Gets the value of the locationGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationGroup() {
        return locationGroup;
    }

    /**
     * Sets the value of the locationGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationGroup(String value) {
        this.locationGroup = value;
    }

}
