//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{FishbowlSDK}DB_ID" minOccurs="0"/>
 *         &lt;element name="PartID" type="{FishbowlSDK}DB_ID" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}Part"/>
 *         &lt;element name="Num" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element ref="{FishbowlSDK}Description" minOccurs="0"/>
 *         &lt;element name="Details" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}UPC" minOccurs="0"/>
 *         &lt;element name="SKU" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Price" type="{FishbowlSDK}PRICETYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}UOM"/>
 *         &lt;element name="DefaultSOItemType" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="DisplayType" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="URL" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Weight" type="{FishbowlSDK}QUANTYPE" minOccurs="0"/>
 *         &lt;element name="WeightUOMID" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="Width" type="{FishbowlSDK}QUANTYPE" minOccurs="0"/>
 *         &lt;element name="Height" type="{FishbowlSDK}QUANTYPE" minOccurs="0"/>
 *         &lt;element name="Len" type="{FishbowlSDK}QUANTYPE" minOccurs="0"/>
 *         &lt;element name="SizeUOMID" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="IncomeAccountID" type="{FishbowlSDK}DB_ID" minOccurs="0"/>
 *         &lt;element name="AccountingID" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="AccountingHash" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="SellableInOtherUOMFlag" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="ActiveFlag" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="TaxableFlag" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="UsePriceFlag" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="KitFlag" type="{FishbowlSDK}BOOLTYPE"/>
 *         &lt;element name="KitGroupedFlag" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="ShowSOComboFlag" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="DateCreated" type="{FishbowlSDK}DATETIMETYPE" minOccurs="0"/>
 *         &lt;element name="DateModified" type="{FishbowlSDK}DATETIMETYPE" minOccurs="0"/>
 *         &lt;element name="Image" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}CustomFields" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "partID",
    "part",
    "num",
    "description",
    "details",
    "upc",
    "sku",
    "price",
    "uom",
    "defaultSOItemType",
    "displayType",
    "url",
    "weight",
    "weightUOMID",
    "width",
    "height",
    "len",
    "sizeUOMID",
    "incomeAccountID",
    "accountingID",
    "accountingHash",
    "sellableInOtherUOMFlag",
    "activeFlag",
    "taxableFlag",
    "usePriceFlag",
    "kitFlag",
    "kitGroupedFlag",
    "showSOComboFlag",
    "dateCreated",
    "dateModified",
    "image",
    "customFields"
})
@XmlRootElement(name = "Product")
public class Product {

    @XmlElement(name = "ID")
    protected BigInteger id;
    @XmlElement(name = "PartID")
    protected BigInteger partID;
    @XmlElement(name = "Part", required = true)
    protected Part part;
    @XmlElement(name = "Num", required = true)
    protected String num;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Details")
    protected String details;
    @XmlElement(name = "UPC")
    protected String upc;
    @XmlElement(name = "SKU")
    protected String sku;
    @XmlElement(name = "Price")
    protected String price;
    @XmlElement(name = "UOM", required = true)
    protected UOM uom;
    @XmlElement(name = "DefaultSOItemType", required = true)
    protected String defaultSOItemType;
    @XmlElement(name = "DisplayType")
    protected String displayType;
    @XmlElement(name = "URL")
    protected String url;
    @XmlElement(name = "Weight")
    protected String weight;
    @XmlElement(name = "WeightUOMID")
    protected BigInteger weightUOMID;
    @XmlElement(name = "Width")
    protected String width;
    @XmlElement(name = "Height")
    protected String height;
    @XmlElement(name = "Len")
    protected String len;
    @XmlElement(name = "SizeUOMID")
    protected BigInteger sizeUOMID;
    @XmlElement(name = "IncomeAccountID")
    protected BigInteger incomeAccountID;
    @XmlElement(name = "AccountingID")
    protected String accountingID;
    @XmlElement(name = "AccountingHash")
    protected String accountingHash;
    @XmlElement(name = "SellableInOtherUOMFlag", defaultValue = "true")
    protected Boolean sellableInOtherUOMFlag;
    @XmlElement(name = "ActiveFlag", defaultValue = "true")
    protected Boolean activeFlag;
    @XmlElement(name = "TaxableFlag", defaultValue = "false")
    protected Boolean taxableFlag;
    @XmlElement(name = "UsePriceFlag", defaultValue = "true")
    protected Boolean usePriceFlag;
    @XmlElement(name = "KitFlag", defaultValue = "false")
    protected boolean kitFlag;
    @XmlElement(name = "KitGroupedFlag", defaultValue = "false")
    protected Boolean kitGroupedFlag;
    @XmlElement(name = "ShowSOComboFlag", defaultValue = "true")
    protected Boolean showSOComboFlag;
    @XmlElement(name = "DateCreated")
    protected String dateCreated;
    @XmlElement(name = "DateModified")
    protected String dateModified;
    @XmlElement(name = "Image")
    protected String image;
    @XmlElement(name = "CustomFields")
    protected CustomFields customFields;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the partID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPartID() {
        return partID;
    }

    /**
     * Sets the value of the partID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPartID(BigInteger value) {
        this.partID = value;
    }

    /**
     * Gets the value of the part property.
     * 
     * @return
     *     possible object is
     *     {@link Part }
     *     
     */
    public Part getPart() {
        return part;
    }

    /**
     * Sets the value of the part property.
     * 
     * @param value
     *     allowed object is
     *     {@link Part }
     *     
     */
    public void setPart(Part value) {
        this.part = value;
    }

    /**
     * Gets the value of the num property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNum() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNum(String value) {
        this.num = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetails(String value) {
        this.details = value;
    }

    /**
     * Gets the value of the upc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPC() {
        return upc;
    }

    /**
     * Sets the value of the upc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPC(String value) {
        this.upc = value;
    }

    /**
     * Gets the value of the sku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKU() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKU(String value) {
        this.sku = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the uom property.
     * 
     * @return
     *     possible object is
     *     {@link UOM }
     *     
     */
    public UOM getUOM() {
        return uom;
    }

    /**
     * Sets the value of the uom property.
     * 
     * @param value
     *     allowed object is
     *     {@link UOM }
     *     
     */
    public void setUOM(UOM value) {
        this.uom = value;
    }

    /**
     * Gets the value of the defaultSOItemType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultSOItemType() {
        return defaultSOItemType;
    }

    /**
     * Sets the value of the defaultSOItemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultSOItemType(String value) {
        this.defaultSOItemType = value;
    }

    /**
     * Gets the value of the displayType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayType() {
        return displayType;
    }

    /**
     * Sets the value of the displayType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayType(String value) {
        this.displayType = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeight(String value) {
        this.weight = value;
    }

    /**
     * Gets the value of the weightUOMID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWeightUOMID() {
        return weightUOMID;
    }

    /**
     * Sets the value of the weightUOMID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWeightUOMID(BigInteger value) {
        this.weightUOMID = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the len property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLen() {
        return len;
    }

    /**
     * Sets the value of the len property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLen(String value) {
        this.len = value;
    }

    /**
     * Gets the value of the sizeUOMID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSizeUOMID() {
        return sizeUOMID;
    }

    /**
     * Sets the value of the sizeUOMID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSizeUOMID(BigInteger value) {
        this.sizeUOMID = value;
    }

    /**
     * Gets the value of the incomeAccountID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIncomeAccountID() {
        return incomeAccountID;
    }

    /**
     * Sets the value of the incomeAccountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIncomeAccountID(BigInteger value) {
        this.incomeAccountID = value;
    }

    /**
     * Gets the value of the accountingID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingID() {
        return accountingID;
    }

    /**
     * Sets the value of the accountingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingID(String value) {
        this.accountingID = value;
    }

    /**
     * Gets the value of the accountingHash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingHash() {
        return accountingHash;
    }

    /**
     * Sets the value of the accountingHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingHash(String value) {
        this.accountingHash = value;
    }

    /**
     * Gets the value of the sellableInOtherUOMFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSellableInOtherUOMFlag() {
        return sellableInOtherUOMFlag;
    }

    /**
     * Sets the value of the sellableInOtherUOMFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSellableInOtherUOMFlag(Boolean value) {
        this.sellableInOtherUOMFlag = value;
    }

    /**
     * Gets the value of the activeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActiveFlag() {
        return activeFlag;
    }

    /**
     * Sets the value of the activeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActiveFlag(Boolean value) {
        this.activeFlag = value;
    }

    /**
     * Gets the value of the taxableFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTaxableFlag() {
        return taxableFlag;
    }

    /**
     * Sets the value of the taxableFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTaxableFlag(Boolean value) {
        this.taxableFlag = value;
    }

    /**
     * Gets the value of the usePriceFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsePriceFlag() {
        return usePriceFlag;
    }

    /**
     * Sets the value of the usePriceFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsePriceFlag(Boolean value) {
        this.usePriceFlag = value;
    }

    /**
     * Gets the value of the kitFlag property.
     * 
     */
    public boolean isKitFlag() {
        return kitFlag;
    }

    /**
     * Sets the value of the kitFlag property.
     * 
     */
    public void setKitFlag(boolean value) {
        this.kitFlag = value;
    }

    /**
     * Gets the value of the kitGroupedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKitGroupedFlag() {
        return kitGroupedFlag;
    }

    /**
     * Sets the value of the kitGroupedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKitGroupedFlag(Boolean value) {
        this.kitGroupedFlag = value;
    }

    /**
     * Gets the value of the showSOComboFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowSOComboFlag() {
        return showSOComboFlag;
    }

    /**
     * Sets the value of the showSOComboFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowSOComboFlag(Boolean value) {
        this.showSOComboFlag = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateCreated(String value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the dateModified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateModified() {
        return dateModified;
    }

    /**
     * Sets the value of the dateModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateModified(String value) {
        this.dateModified = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the customFields property.
     * 
     * @return
     *     possible object is
     *     {@link CustomFields }
     *     
     */
    public CustomFields getCustomFields() {
        return customFields;
    }

    /**
     * Sets the value of the customFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomFields }
     *     
     */
    public void setCustomFields(CustomFields value) {
        this.customFields = value;
    }

}
