//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RMAID" type="{FishbowlSDK}DB_ID"/>
 *         &lt;element name="Number" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="CustomerName" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="Status" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="LocationGroup" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="DateCreated" type="{FishbowlSDK}DATETIMETYPE" minOccurs="0"/>
 *         &lt;element name="DateExpires" type="{FishbowlSDK}DATETIMETYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}RMAItems"/>
 *         &lt;element ref="{FishbowlSDK}CustomFields" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}Memos" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rmaid",
    "number",
    "customerName",
    "status",
    "locationGroup",
    "dateCreated",
    "dateExpires",
    "rmaItems",
    "customFields",
    "memos"
})
@XmlRootElement(name = "RMA")
public class RMA {

    @XmlElement(name = "RMAID", required = true)
    protected BigInteger rmaid;
    @XmlElement(name = "Number", required = true)
    protected String number;
    @XmlElement(name = "CustomerName", required = true)
    protected String customerName;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "LocationGroup", required = true)
    protected String locationGroup;
    @XmlElement(name = "DateCreated")
    protected String dateCreated;
    @XmlElement(name = "DateExpires")
    protected String dateExpires;
    @XmlElement(name = "RMAItems", required = true)
    protected RMAItems rmaItems;
    @XmlElement(name = "CustomFields")
    protected CustomFields customFields;
    @XmlElement(name = "Memos")
    protected Memos memos;

    /**
     * Gets the value of the rmaid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRMAID() {
        return rmaid;
    }

    /**
     * Sets the value of the rmaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRMAID(BigInteger value) {
        this.rmaid = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the locationGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationGroup() {
        return locationGroup;
    }

    /**
     * Sets the value of the locationGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationGroup(String value) {
        this.locationGroup = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateCreated(String value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the dateExpires property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateExpires() {
        return dateExpires;
    }

    /**
     * Sets the value of the dateExpires property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateExpires(String value) {
        this.dateExpires = value;
    }

    /**
     * Gets the value of the rmaItems property.
     * 
     * @return
     *     possible object is
     *     {@link RMAItems }
     *     
     */
    public RMAItems getRMAItems() {
        return rmaItems;
    }

    /**
     * Sets the value of the rmaItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link RMAItems }
     *     
     */
    public void setRMAItems(RMAItems value) {
        this.rmaItems = value;
    }

    /**
     * Gets the value of the customFields property.
     * 
     * @return
     *     possible object is
     *     {@link CustomFields }
     *     
     */
    public CustomFields getCustomFields() {
        return customFields;
    }

    /**
     * Sets the value of the customFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomFields }
     *     
     */
    public void setCustomFields(CustomFields value) {
        this.customFields = value;
    }

    /**
     * Gets the value of the memos property.
     * 
     * @return
     *     possible object is
     *     {@link Memos }
     *     
     */
    public Memos getMemos() {
        return memos;
    }

    /**
     * Sets the value of the memos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Memos }
     *     
     */
    public void setMemos(Memos value) {
        this.memos = value;
    }

}
