//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LinkID" type="{FishbowlSDK}DB_ID"/>
 *         &lt;element name="Type" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="FromTable" type="{FishbowlSDK}INTTYPE"/>
 *         &lt;element name="FromRecord" type="{FishbowlSDK}DB_ID"/>
 *         &lt;element name="ToTable" type="{FishbowlSDK}INTTYPE"/>
 *         &lt;element name="ToRecord" type="{FishbowlSDK}DB_ID"/>
 *         &lt;element name="Description" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="OrderType" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="OrderNum" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="OrderStatus" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "linkID",
    "type",
    "fromTable",
    "fromRecord",
    "toTable",
    "toRecord",
    "description",
    "orderType",
    "orderNum",
    "orderStatus"
})
@XmlRootElement(name = "RMAItemLink")
public class RMAItemLink {

    @XmlElement(name = "LinkID", required = true)
    protected BigInteger linkID;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "FromTable", required = true)
    protected BigInteger fromTable;
    @XmlElement(name = "FromRecord", required = true)
    protected BigInteger fromRecord;
    @XmlElement(name = "ToTable", required = true)
    protected BigInteger toTable;
    @XmlElement(name = "ToRecord", required = true)
    protected BigInteger toRecord;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "OrderType")
    protected String orderType;
    @XmlElement(name = "OrderNum")
    protected String orderNum;
    @XmlElement(name = "OrderStatus")
    protected String orderStatus;

    /**
     * Gets the value of the linkID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLinkID() {
        return linkID;
    }

    /**
     * Sets the value of the linkID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLinkID(BigInteger value) {
        this.linkID = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the fromTable property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFromTable() {
        return fromTable;
    }

    /**
     * Sets the value of the fromTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFromTable(BigInteger value) {
        this.fromTable = value;
    }

    /**
     * Gets the value of the fromRecord property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFromRecord() {
        return fromRecord;
    }

    /**
     * Sets the value of the fromRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFromRecord(BigInteger value) {
        this.fromRecord = value;
    }

    /**
     * Gets the value of the toTable property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getToTable() {
        return toTable;
    }

    /**
     * Sets the value of the toTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setToTable(BigInteger value) {
        this.toTable = value;
    }

    /**
     * Gets the value of the toRecord property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getToRecord() {
        return toRecord;
    }

    /**
     * Sets the value of the toRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setToRecord(BigInteger value) {
        this.toRecord = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the orderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the orderNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * Sets the value of the orderNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNum(String value) {
        this.orderNum = value;
    }

    /**
     * Gets the value of the orderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * Sets the value of the orderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderStatus(String value) {
        this.orderStatus = value;
    }

}
