//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{FishbowlSDK}DB_ID" minOccurs="0"/>
 *         &lt;element name="Note" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="TotalPrice" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="TotalTax" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="PaymentTotal" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="ItemTotal" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Salesman" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Number" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Status" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="Carrier" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="FirstShipDate" type="{FishbowlSDK}DATETIMETYPE" minOccurs="0"/>
 *         &lt;element name="CreatedDate" type="{FishbowlSDK}DATETIMETYPE" minOccurs="0"/>
 *         &lt;element name="IssuedDate" type="{FishbowlSDK}DATETIMETYPE" minOccurs="0"/>
 *         &lt;element name="TaxRatePercentage" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="TaxRateName" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="ShippingCost" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="ShippingTerms" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="PaymentTerms" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="CustomerContact" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="CustomerName" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="FOB" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="QuickBooksClassName" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="LocationGroup" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="BillTo" type="{FishbowlSDK}BillType" minOccurs="0"/>
 *         &lt;element name="Ship" type="{FishbowlSDK}ShipType" minOccurs="0"/>
 *         &lt;element name="IssueFlag" type="{FishbowlSDK}BOOLTYPE"/>
 *         &lt;element name="VendorPO" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="CustomerPO" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}CustomFields" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}Memos" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}SalesOrderItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}Items" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "note",
    "totalPrice",
    "totalTax",
    "paymentTotal",
    "itemTotal",
    "salesman",
    "number",
    "status",
    "carrier",
    "firstShipDate",
    "createdDate",
    "issuedDate",
    "taxRatePercentage",
    "taxRateName",
    "shippingCost",
    "shippingTerms",
    "paymentTerms",
    "customerContact",
    "customerName",
    "fob",
    "quickBooksClassName",
    "locationGroup",
    "billTo",
    "ship",
    "issueFlag",
    "vendorPO",
    "customerPO",
    "customFields",
    "memos",
    "salesOrderItem",
    "items"
})
@XmlRootElement(name = "SalesOrder")
public class SalesOrder {

    @XmlElement(name = "ID")
    protected BigInteger id;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "TotalPrice")
    protected String totalPrice;
    @XmlElement(name = "TotalTax")
    protected String totalTax;
    @XmlElement(name = "PaymentTotal")
    protected String paymentTotal;
    @XmlElement(name = "ItemTotal")
    protected String itemTotal;
    @XmlElement(name = "Salesman")
    protected String salesman;
    @XmlElement(name = "Number")
    protected String number;
    @XmlElement(name = "Status")
    protected BigInteger status;
    @XmlElement(name = "Carrier")
    protected String carrier;
    @XmlElement(name = "FirstShipDate")
    protected String firstShipDate;
    @XmlElement(name = "CreatedDate")
    protected String createdDate;
    @XmlElement(name = "IssuedDate")
    protected String issuedDate;
    @XmlElement(name = "TaxRatePercentage")
    protected String taxRatePercentage;
    @XmlElement(name = "TaxRateName")
    protected String taxRateName;
    @XmlElement(name = "ShippingCost")
    protected String shippingCost;
    @XmlElement(name = "ShippingTerms")
    protected String shippingTerms;
    @XmlElement(name = "PaymentTerms")
    protected String paymentTerms;
    @XmlElement(name = "CustomerContact")
    protected String customerContact;
    @XmlElement(name = "CustomerName", required = true)
    protected String customerName;
    @XmlElement(name = "FOB")
    protected String fob;
    @XmlElement(name = "QuickBooksClassName")
    protected String quickBooksClassName;
    @XmlElement(name = "LocationGroup")
    protected String locationGroup;
    @XmlElement(name = "BillTo")
    protected BillType billTo;
    @XmlElement(name = "Ship")
    protected ShipType ship;
    @XmlElement(name = "IssueFlag", defaultValue = "false")
    protected boolean issueFlag;
    @XmlElement(name = "VendorPO")
    protected String vendorPO;
    @XmlElement(name = "CustomerPO")
    protected String customerPO;
    @XmlElement(name = "CustomFields")
    protected CustomFields customFields;
    @XmlElement(name = "Memos")
    protected Memos memos;
    @XmlElement(name = "SalesOrderItem")
    protected List<SalesOrderItem> salesOrderItem;
    @XmlElement(name = "Items")
    protected Items items;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the totalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the value of the totalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalPrice(String value) {
        this.totalPrice = value;
    }

    /**
     * Gets the value of the totalTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalTax() {
        return totalTax;
    }

    /**
     * Sets the value of the totalTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalTax(String value) {
        this.totalTax = value;
    }

    /**
     * Gets the value of the paymentTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTotal() {
        return paymentTotal;
    }

    /**
     * Sets the value of the paymentTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTotal(String value) {
        this.paymentTotal = value;
    }

    /**
     * Gets the value of the itemTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemTotal() {
        return itemTotal;
    }

    /**
     * Sets the value of the itemTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemTotal(String value) {
        this.itemTotal = value;
    }

    /**
     * Gets the value of the salesman property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesman() {
        return salesman;
    }

    /**
     * Sets the value of the salesman property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesman(String value) {
        this.salesman = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatus(BigInteger value) {
        this.status = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrier(String value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the firstShipDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstShipDate() {
        return firstShipDate;
    }

    /**
     * Sets the value of the firstShipDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstShipDate(String value) {
        this.firstShipDate = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDate(String value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the issuedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuedDate() {
        return issuedDate;
    }

    /**
     * Sets the value of the issuedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuedDate(String value) {
        this.issuedDate = value;
    }

    /**
     * Gets the value of the taxRatePercentage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxRatePercentage() {
        return taxRatePercentage;
    }

    /**
     * Sets the value of the taxRatePercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxRatePercentage(String value) {
        this.taxRatePercentage = value;
    }

    /**
     * Gets the value of the taxRateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxRateName() {
        return taxRateName;
    }

    /**
     * Sets the value of the taxRateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxRateName(String value) {
        this.taxRateName = value;
    }

    /**
     * Gets the value of the shippingCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingCost() {
        return shippingCost;
    }

    /**
     * Sets the value of the shippingCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingCost(String value) {
        this.shippingCost = value;
    }

    /**
     * Gets the value of the shippingTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingTerms() {
        return shippingTerms;
    }

    /**
     * Sets the value of the shippingTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingTerms(String value) {
        this.shippingTerms = value;
    }

    /**
     * Gets the value of the paymentTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTerms() {
        return paymentTerms;
    }

    /**
     * Sets the value of the paymentTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTerms(String value) {
        this.paymentTerms = value;
    }

    /**
     * Gets the value of the customerContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerContact() {
        return customerContact;
    }

    /**
     * Sets the value of the customerContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerContact(String value) {
        this.customerContact = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the fob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOB() {
        return fob;
    }

    /**
     * Sets the value of the fob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOB(String value) {
        this.fob = value;
    }

    /**
     * Gets the value of the quickBooksClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuickBooksClassName() {
        return quickBooksClassName;
    }

    /**
     * Sets the value of the quickBooksClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuickBooksClassName(String value) {
        this.quickBooksClassName = value;
    }

    /**
     * Gets the value of the locationGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationGroup() {
        return locationGroup;
    }

    /**
     * Sets the value of the locationGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationGroup(String value) {
        this.locationGroup = value;
    }

    /**
     * Gets the value of the billTo property.
     * 
     * @return
     *     possible object is
     *     {@link BillType }
     *     
     */
    public BillType getBillTo() {
        return billTo;
    }

    /**
     * Sets the value of the billTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillType }
     *     
     */
    public void setBillTo(BillType value) {
        this.billTo = value;
    }

    /**
     * Gets the value of the ship property.
     * 
     * @return
     *     possible object is
     *     {@link ShipType }
     *     
     */
    public ShipType getShip() {
        return ship;
    }

    /**
     * Sets the value of the ship property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipType }
     *     
     */
    public void setShip(ShipType value) {
        this.ship = value;
    }

    /**
     * Gets the value of the issueFlag property.
     * 
     */
    public boolean isIssueFlag() {
        return issueFlag;
    }

    /**
     * Sets the value of the issueFlag property.
     * 
     */
    public void setIssueFlag(boolean value) {
        this.issueFlag = value;
    }

    /**
     * Gets the value of the vendorPO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorPO() {
        return vendorPO;
    }

    /**
     * Sets the value of the vendorPO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorPO(String value) {
        this.vendorPO = value;
    }

    /**
     * Gets the value of the customerPO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPO() {
        return customerPO;
    }

    /**
     * Sets the value of the customerPO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPO(String value) {
        this.customerPO = value;
    }

    /**
     * Gets the value of the customFields property.
     * 
     * @return
     *     possible object is
     *     {@link CustomFields }
     *     
     */
    public CustomFields getCustomFields() {
        return customFields;
    }

    /**
     * Sets the value of the customFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomFields }
     *     
     */
    public void setCustomFields(CustomFields value) {
        this.customFields = value;
    }

    /**
     * Gets the value of the memos property.
     * 
     * @return
     *     possible object is
     *     {@link Memos }
     *     
     */
    public Memos getMemos() {
        return memos;
    }

    /**
     * Sets the value of the memos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Memos }
     *     
     */
    public void setMemos(Memos value) {
        this.memos = value;
    }

    /**
     * Gets the value of the salesOrderItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the salesOrderItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSalesOrderItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SalesOrderItem }
     * 
     * 
     */
    public List<SalesOrderItem> getSalesOrderItem() {
        if (salesOrderItem == null) {
            salesOrderItem = new ArrayList<SalesOrderItem>();
        }
        return this.salesOrderItem;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link Items }
     *     
     */
    public Items getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link Items }
     *     
     */
    public void setItems(Items value) {
        this.items = value;
    }

}
