//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SerialID" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="SerialNumID" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Number" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element ref="{FishbowlSDK}PartTracking"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serialID",
    "serialNumID",
    "number",
    "partTracking"
})
@XmlRootElement(name = "SerialNum")
public class SerialNum {

    @XmlElement(name = "SerialID")
    protected Object serialID;
    @XmlElement(name = "SerialNumID")
    protected Object serialNumID;
    @XmlElement(name = "Number", required = true)
    protected String number;
    @XmlElement(name = "PartTracking", required = true)
    protected PartTracking partTracking;

    /**
     * Gets the value of the serialID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSerialID() {
        return serialID;
    }

    /**
     * Sets the value of the serialID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSerialID(Object value) {
        this.serialID = value;
    }

    /**
     * Gets the value of the serialNumID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSerialNumID() {
        return serialNumID;
    }

    /**
     * Sets the value of the serialNumID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSerialNumID(Object value) {
        this.serialNumID = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the partTracking property.
     * 
     * @return
     *     possible object is
     *     {@link PartTracking }
     *     
     */
    public PartTracking getPartTracking() {
        return partTracking;
    }

    /**
     * Sets the value of the partTracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartTracking }
     *     
     */
    public void setPartTracking(PartTracking value) {
        this.partTracking = value;
    }

}
