//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShipRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipRqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShipDate" type="{FishbowlSDK}DATETYPE" minOccurs="0"/>
 *         &lt;element name="FulfillService" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="AllowEntered" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}OrderNums"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipRqType", propOrder = {
    "shipDate",
    "fulfillService",
    "allowEntered",
    "orderNums"
})
public class ShipRqType {

    @XmlElement(name = "ShipDate")
    protected String shipDate;
    @XmlElement(name = "FulfillService")
    protected String fulfillService;
    @XmlElement(name = "AllowEntered")
    protected String allowEntered;
    @XmlElement(name = "OrderNums", required = true)
    protected OrderNums orderNums;

    /**
     * Gets the value of the shipDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipDate() {
        return shipDate;
    }

    /**
     * Sets the value of the shipDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipDate(String value) {
        this.shipDate = value;
    }

    /**
     * Gets the value of the fulfillService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfillService() {
        return fulfillService;
    }

    /**
     * Sets the value of the fulfillService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfillService(String value) {
        this.fulfillService = value;
    }

    /**
     * Gets the value of the allowEntered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowEntered() {
        return allowEntered;
    }

    /**
     * Sets the value of the allowEntered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowEntered(String value) {
        this.allowEntered = value;
    }

    /**
     * Gets the value of the orderNums property.
     * 
     * @return
     *     possible object is
     *     {@link OrderNums }
     *     
     */
    public OrderNums getOrderNums() {
        return orderNums;
    }

    /**
     * Sets the value of the orderNums property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderNums }
     *     
     */
    public void setOrderNums(OrderNums value) {
        this.orderNums = value;
    }

}
