//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TagMoveRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TagMoveRqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SrcTagNum" type="{FishbowlSDK}INTTYPE"/>
 *         &lt;element name="DstTagNum" type="{FishbowlSDK}INTTYPE"/>
 *         &lt;element name="Note" type="{FishbowlSDK}STRTYPE"/>
 *       &lt;/sequence>
 *       &lt;attribute name="requestID" type="{FishbowlSDK}STRTYPE" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TagMoveRqType", propOrder = {
    "srcTagNum",
    "dstTagNum",
    "note"
})
public class TagMoveRqType {

    @XmlElement(name = "SrcTagNum", required = true)
    protected BigInteger srcTagNum;
    @XmlElement(name = "DstTagNum", required = true)
    protected BigInteger dstTagNum;
    @XmlElement(name = "Note", required = true)
    protected String note;
    @XmlAttribute(name = "requestID")
    protected String requestID;

    /**
     * Gets the value of the srcTagNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSrcTagNum() {
        return srcTagNum;
    }

    /**
     * Sets the value of the srcTagNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSrcTagNum(BigInteger value) {
        this.srcTagNum = value;
    }

    /**
     * Gets the value of the dstTagNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDstTagNum() {
        return dstTagNum;
    }

    /**
     * Sets the value of the dstTagNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDstTagNum(BigInteger value) {
        this.dstTagNum = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }

}
