//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{FishbowlSDK}VendorID" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}AccountID" minOccurs="0"/>
 *         &lt;element name="Status" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="DefPaymentTerms" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="DefShipTerms" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="TaxRate" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Name" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Number" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="DateCreated" type="{FishbowlSDK}DATETIMETYPE" minOccurs="0"/>
 *         &lt;element name="DateModified" type="{FishbowlSDK}DATETIMETYPE" minOccurs="0"/>
 *         &lt;element name="LastChangedUser" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="CreditLimit" type="{FishbowlSDK}PRICETYPE" minOccurs="0"/>
 *         &lt;element name="Note" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="AysUserID" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element name="ActiveFlag" type="{FishbowlSDK}BOOLTYPE" minOccurs="0"/>
 *         &lt;element name="AccountingID" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="AccountingHash" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="LeadTime" type="{FishbowlSDK}INTTYPE" minOccurs="0"/>
 *         &lt;element ref="{FishbowlSDK}Addresses" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vendorID",
    "accountID",
    "status",
    "defPaymentTerms",
    "defShipTerms",
    "taxRate",
    "name",
    "number",
    "dateCreated",
    "dateModified",
    "lastChangedUser",
    "creditLimit",
    "note",
    "aysUserID",
    "activeFlag",
    "accountingID",
    "accountingHash",
    "leadTime",
    "addresses"
})
@XmlRootElement(name = "Vendor")
public class Vendor {

    @XmlElement(name = "VendorID")
    protected BigInteger vendorID;
    @XmlElement(name = "AccountID")
    protected BigInteger accountID;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "DefPaymentTerms")
    protected String defPaymentTerms;
    @XmlElement(name = "DefShipTerms")
    protected String defShipTerms;
    @XmlElement(name = "TaxRate")
    protected String taxRate;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Number")
    protected String number;
    @XmlElement(name = "DateCreated")
    protected String dateCreated;
    @XmlElement(name = "DateModified")
    protected String dateModified;
    @XmlElement(name = "LastChangedUser")
    protected String lastChangedUser;
    @XmlElement(name = "CreditLimit")
    protected String creditLimit;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "AysUserID")
    protected BigInteger aysUserID;
    @XmlElement(name = "ActiveFlag")
    protected Boolean activeFlag;
    @XmlElement(name = "AccountingID")
    protected String accountingID;
    @XmlElement(name = "AccountingHash")
    protected String accountingHash;
    @XmlElement(name = "LeadTime")
    protected BigInteger leadTime;
    @XmlElement(name = "Addresses")
    protected Addresses addresses;

    /**
     * Gets the value of the vendorID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVendorID() {
        return vendorID;
    }

    /**
     * Sets the value of the vendorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVendorID(BigInteger value) {
        this.vendorID = value;
    }

    /**
     * Gets the value of the accountID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountID() {
        return accountID;
    }

    /**
     * Sets the value of the accountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountID(BigInteger value) {
        this.accountID = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the defPaymentTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefPaymentTerms() {
        return defPaymentTerms;
    }

    /**
     * Sets the value of the defPaymentTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefPaymentTerms(String value) {
        this.defPaymentTerms = value;
    }

    /**
     * Gets the value of the defShipTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefShipTerms() {
        return defShipTerms;
    }

    /**
     * Sets the value of the defShipTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefShipTerms(String value) {
        this.defShipTerms = value;
    }

    /**
     * Gets the value of the taxRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxRate() {
        return taxRate;
    }

    /**
     * Sets the value of the taxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxRate(String value) {
        this.taxRate = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateCreated(String value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the dateModified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateModified() {
        return dateModified;
    }

    /**
     * Sets the value of the dateModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateModified(String value) {
        this.dateModified = value;
    }

    /**
     * Gets the value of the lastChangedUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastChangedUser() {
        return lastChangedUser;
    }

    /**
     * Sets the value of the lastChangedUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastChangedUser(String value) {
        this.lastChangedUser = value;
    }

    /**
     * Gets the value of the creditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditLimit() {
        return creditLimit;
    }

    /**
     * Sets the value of the creditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditLimit(String value) {
        this.creditLimit = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the aysUserID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAysUserID() {
        return aysUserID;
    }

    /**
     * Sets the value of the aysUserID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAysUserID(BigInteger value) {
        this.aysUserID = value;
    }

    /**
     * Gets the value of the activeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActiveFlag() {
        return activeFlag;
    }

    /**
     * Sets the value of the activeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActiveFlag(Boolean value) {
        this.activeFlag = value;
    }

    /**
     * Gets the value of the accountingID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingID() {
        return accountingID;
    }

    /**
     * Sets the value of the accountingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingID(String value) {
        this.accountingID = value;
    }

    /**
     * Gets the value of the accountingHash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingHash() {
        return accountingHash;
    }

    /**
     * Sets the value of the accountingHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingHash(String value) {
        this.accountingHash = value;
    }

    /**
     * Gets the value of the leadTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLeadTime() {
        return leadTime;
    }

    /**
     * Sets the value of the leadTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLeadTime(BigInteger value) {
        this.leadTime = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link Addresses }
     *     
     */
    public Addresses getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addresses }
     *     
     */
    public void setAddresses(Addresses value) {
        this.addresses = value;
    }

}
