//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.10 at 12:16:50 AM IST 
//


package com.abhi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for YieldRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="YieldRqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TagNum" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="DestinationTagNum" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="Location" type="{FishbowlSDK}STRTYPE" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{FishbowlSDK}STRTYPE"/>
 *         &lt;element name="Ref" type="{FishbowlSDK}STRTYPE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "YieldRqType", propOrder = {
    "tagNum",
    "destinationTagNum",
    "location",
    "quantity",
    "ref"
})
public class YieldRqType {

    @XmlElement(name = "TagNum", required = true)
    protected String tagNum;
    @XmlElement(name = "DestinationTagNum", required = true)
    protected String destinationTagNum;
    @XmlElement(name = "Location")
    protected String location;
    @XmlElement(name = "Quantity", required = true)
    protected String quantity;
    @XmlElement(name = "Ref", required = true)
    protected String ref;

    /**
     * Gets the value of the tagNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTagNum() {
        return tagNum;
    }

    /**
     * Sets the value of the tagNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTagNum(String value) {
        this.tagNum = value;
    }

    /**
     * Gets the value of the destinationTagNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationTagNum() {
        return destinationTagNum;
    }

    /**
     * Sets the value of the destinationTagNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationTagNum(String value) {
        this.destinationTagNum = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantity(String value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

}
